/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 10-Apr-2007.
 */
#ifndef RANAPCLASS_H
#define RANAPCLASS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1per.h"
#include "rtTable.h"
#include "ranap.h"

/* Class definitions */

/**************************************************************/
/*                                                            */
/*  RANAP_PROTOCOL_IES                                        */
/*                                                            */
/**************************************************************/

typedef struct RANAP_PROTOCOL_IES {
   OSUINT16 id;
   OSUINT32 criticality;
   int ValueSize;
   int (*decodeValue) (ASN1CTXT* , void * );
   void (*printValue) (ASN1ConstCharPtr , void * );
   OSUINT32 presence;
} RANAP_PROTOCOL_IES;

/**************************************************************/
/*                                                            */
/*  RANAP_PROTOCOL_IES_PAIR                                   */
/*                                                            */
/**************************************************************/

typedef struct RANAP_PROTOCOL_IES_PAIR {
   OSUINT16 id;
   OSUINT32 firstCriticality;
   int FirstValueSize;
   int (*decodeFirstValue) (ASN1CTXT* , void * );
   void (*printFirstValue) (ASN1ConstCharPtr , void * );
   OSUINT32 secondCriticality;
   int SecondValueSize;
   int (*decodeSecondValue) (ASN1CTXT* , void * );
   void (*printSecondValue) (ASN1ConstCharPtr , void * );
   OSUINT32 presence;
} RANAP_PROTOCOL_IES_PAIR;

/**************************************************************/
/*                                                            */
/*  RANAP_PROTOCOL_EXTENSION                                  */
/*                                                            */
/**************************************************************/

typedef struct RANAP_PROTOCOL_EXTENSION {
   OSUINT16 id;
   OSUINT32 criticality;
   int ExtensionSize;
   int (*decodeExtension) (ASN1CTXT* , void * );
   void (*printExtension) (ASN1ConstCharPtr , void * );
   OSUINT32 presence;
} RANAP_PROTOCOL_EXTENSION;

/**************************************************************/
/*                                                            */
/*  RANAP_PRIVATE_IES                                         */
/*                                                            */
/**************************************************************/

typedef struct RANAP_PRIVATE_IES {
   PrivateIE_ID id;
   OSUINT32 criticality;
   int ValueSize;
   int (*decodeValue) (ASN1CTXT* , void * );
   void (*printValue) (ASN1ConstCharPtr , void * );
   OSUINT32 presence;
} RANAP_PRIVATE_IES;

/* Class definitions */

/**************************************************************/
/*                                                            */
/*  RANAP_ELEMENTARY_PROCEDURE                                */
/*                                                            */
/**************************************************************/

typedef struct RANAP_ELEMENTARY_PROCEDURE {
   struct {
      unsigned SuccessfulOutcomePresent : 1;
      unsigned UnsuccessfulOutcomePresent : 1;
      unsigned OutcomePresent : 1;
      unsigned criticalityPresent : 1;
   } m;
   int InitiatingMessageSize;
   int (*decodeInitiatingMessage) (ASN1CTXT* , void * );
   void (*printInitiatingMessage) (ASN1ConstCharPtr , void * );
   int SuccessfulOutcomeSize;
   int (*decodeSuccessfulOutcome) (ASN1CTXT* , void * );
   void (*printSuccessfulOutcome) (ASN1ConstCharPtr , void * );
   int UnsuccessfulOutcomeSize;
   int (*decodeUnsuccessfulOutcome) (ASN1CTXT* , void * );
   void (*printUnsuccessfulOutcome) (ASN1ConstCharPtr , void * );
   int OutcomeSize;
   int (*decodeOutcome) (ASN1CTXT* , void * );
   void (*printOutcome) (ASN1ConstCharPtr , void * );
   OSUINT8 procedureCode;
   OSUINT32 criticality;
} RANAP_ELEMENTARY_PROCEDURE;

#ifdef __cplusplus
}
#endif

#endif
