/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 19-Mar-2007.
 */
#include "asn1intl.h"
#include "NBAP-Containers.h"
#include "NBAP-CommonDataTypes.h"

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Field                                          */
/*                                                            */
/**************************************************************/

ProtocolIE_Field* asn1Test_ProtocolIE_Field
   (ASN1CTXT* pctxt)
{
   ProtocolIE_Field* pvalue = (ProtocolIE_Field*)rtMemAllocZ (pctxt, sizeof(ProtocolIE_Field));
   memset((void*)pvalue, 0, sizeof(ProtocolIE_Field));

   /* Start populating the Sequence or Set type */

   /* Populate the Integer type */
   pvalue->id = 27015;

   /* Populate the Enumerated type */
   pvalue->criticality = reject;

   /* Populate OpenType */
   /* Populate open type with encoded string
      - example uses arbitray string, users 
      should populate the encoded string of 
      appropriate type. The "-tables" option
      of compiler supports appropriate type 
      encoded string generation. */
   {
      static const OSOCTET testdata[] = {0x04, 0x08, 
      0x2b, 0x9, 0x19, 0x72, 0xd, 0x36, 0x10, 0x58,  };
      pvalue->value.data = (ASN1ConstOctetPtr)rtMemAllocZ(pctxt, 10);
      pvalue->value.numocts = 10;
      memcpy ((void*)pvalue->value.data, testdata, 10);
   }
   /* End of Sequence or Set type */
   return (pvalue);
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Single_Container                               */
/*                                                            */
/**************************************************************/

ProtocolIE_Single_Container* asn1Test_ProtocolIE_Single_Container
   (ASN1CTXT* pctxt)
{
   ProtocolIE_Single_Container* pvalue = (ProtocolIE_Single_Container*)rtMemAllocZ (pctxt, sizeof(ProtocolIE_Single_Container));
   memset((void*)pvalue, 0, sizeof(ProtocolIE_Single_Container));

   /* Start populating the Sequence or Set type */

   /* Populate the Integer type */
   pvalue->id = 47788;

   /* Populate the Enumerated type */
   pvalue->criticality = reject;

   /* Populate OpenType */
   /* Populate open type with encoded string
      - example uses arbitray string, users 
      should populate the encoded string of 
      appropriate type. The "-tables" option
      of compiler supports appropriate type 
      encoded string generation. */
   {
      static const OSOCTET testdata[] = {0x04, 0x08, 
      0x83, 0xf1, 0x89, 0xe7, 0x18, 0xf, 0xfc, 0xab,  };
      pvalue->value.data = (ASN1ConstOctetPtr)rtMemAllocZ(pctxt, 10);
      pvalue->value.numocts = 10;
      memcpy ((void*)pvalue->value.data, testdata, 10);
   }
   /* End of Sequence or Set type */
   return (pvalue);
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_ContainerPair                                  */
/*                                                            */
/**************************************************************/

ProtocolIE_ContainerPair* asn1Test_ProtocolIE_ContainerPair
   (ASN1CTXT* pctxt)
{
   ProtocolIE_ContainerPair* pvalue = (ProtocolIE_ContainerPair*)rtMemAllocZ (pctxt, sizeof(ProtocolIE_ContainerPair));
   memset((void*)pvalue, 0, sizeof(ProtocolIE_ContainerPair));

   /* Start populating the Sequence Of type */

   {
      ProtocolIE_ContainerPair *plist = pvalue;
   }
   /* End of Sequence Of type */
   return (pvalue);
}

