/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 19-Mar-2007.
 */
#include "asn1intl.h"
#include "NBAP-PDU-Discriptions.h"
#include "rtPrint.h"

/**************************************************************/
/*                                                            */
/*  InitiatingMessage                                         */
/*                                                            */
/**************************************************************/

void asn1Print_InitiatingMessage
   (const char* name, InitiatingMessage* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.procedureID", name);
   asn1Print_ProcedureID (namebuf, &pvalue->procedureID);

   sprintf (namebuf, "%s.criticality", name);
   asn1Print_Criticality (namebuf, &pvalue->criticality);

   sprintf (namebuf, "%s.messageDiscriminator", name);
   asn1Print_MessageDiscriminator (namebuf, &pvalue->messageDiscriminator);

   sprintf (namebuf, "%s.transactionID", name);
   asn1Print_TransactionID (namebuf, &pvalue->transactionID);

   sprintf (namebuf, "%s.value", name);
   rtPrintOpenType (namebuf,
      pvalue->value.numocts,
      pvalue->value.data, ".");

}

/**************************************************************/
/*                                                            */
/*  SuccessfulOutcome                                         */
/*                                                            */
/**************************************************************/

void asn1Print_SuccessfulOutcome
   (const char* name, SuccessfulOutcome* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.procedureID", name);
   asn1Print_ProcedureID (namebuf, &pvalue->procedureID);

   sprintf (namebuf, "%s.criticality", name);
   asn1Print_Criticality (namebuf, &pvalue->criticality);

   sprintf (namebuf, "%s.messageDiscriminator", name);
   asn1Print_MessageDiscriminator (namebuf, &pvalue->messageDiscriminator);

   sprintf (namebuf, "%s.transactionID", name);
   asn1Print_TransactionID (namebuf, &pvalue->transactionID);

   sprintf (namebuf, "%s.value", name);
   rtPrintOpenType (namebuf,
      pvalue->value.numocts,
      pvalue->value.data, ".");

}

/**************************************************************/
/*                                                            */
/*  UnsuccessfulOutcome                                       */
/*                                                            */
/**************************************************************/

void asn1Print_UnsuccessfulOutcome
   (const char* name, UnsuccessfulOutcome* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.procedureID", name);
   asn1Print_ProcedureID (namebuf, &pvalue->procedureID);

   sprintf (namebuf, "%s.criticality", name);
   asn1Print_Criticality (namebuf, &pvalue->criticality);

   sprintf (namebuf, "%s.messageDiscriminator", name);
   asn1Print_MessageDiscriminator (namebuf, &pvalue->messageDiscriminator);

   sprintf (namebuf, "%s.transactionID", name);
   asn1Print_TransactionID (namebuf, &pvalue->transactionID);

   sprintf (namebuf, "%s.value", name);
   rtPrintOpenType (namebuf,
      pvalue->value.numocts,
      pvalue->value.data, ".");

}

/**************************************************************/
/*                                                            */
/*  Outcome                                                   */
/*                                                            */
/**************************************************************/

void asn1Print_Outcome
   (const char* name, Outcome* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.procedureID", name);
   asn1Print_ProcedureID (namebuf, &pvalue->procedureID);

   sprintf (namebuf, "%s.criticality", name);
   asn1Print_Criticality (namebuf, &pvalue->criticality);

   sprintf (namebuf, "%s.messageDiscriminator", name);
   asn1Print_MessageDiscriminator (namebuf, &pvalue->messageDiscriminator);

   sprintf (namebuf, "%s.transactionID", name);
   asn1Print_TransactionID (namebuf, &pvalue->transactionID);

   sprintf (namebuf, "%s.value", name);
   rtPrintOpenType (namebuf,
      pvalue->value.numocts,
      pvalue->value.data, ".");

}

/**************************************************************/
/*                                                            */
/*  NBAP_PDU                                                  */
/*                                                            */
/**************************************************************/

void asn1Print_NBAP_PDU
   (const char* name, NBAP_PDU* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t) {
      case 1:
         sprintf (namebuf, "%s.u.initiatingMessage", name);
         asn1Print_InitiatingMessage (namebuf, pvalue->u.initiatingMessage);
         break;

      case 2:
         sprintf (namebuf, "%s.u.succesfulOutcome", name);
         asn1Print_SuccessfulOutcome (namebuf, pvalue->u.succesfulOutcome);
         break;

      case 3:
         sprintf (namebuf, "%s.u.unsuccesfulOutcome", name);
         asn1Print_UnsuccessfulOutcome (namebuf, pvalue->u.unsuccesfulOutcome);
         break;

      case 4:
         sprintf (namebuf, "%s.u.outcome", name);
         asn1Print_Outcome (namebuf, pvalue->u.outcome);
         break;

      case 5:
         sprintf (namebuf, "%s.u.extElem1", name);
         rtPrintOpenType (namebuf,
            pvalue->u.extElem1->numocts,
            pvalue->u.extElem1->data, ".");
         break;

      default:;
   }
}

