/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 19-Mar-2007.
 */
#include "asn1intl.h"
#include "NBAP-CommonDataTypes.h"
#include "rtPrint.h"

/**************************************************************/
/*                                                            */
/*  ProcedureCode                                             */
/*                                                            */
/**************************************************************/

void asn1Print_ProcedureCode
   (const char* name, ProcedureCode* pvalue)
{
   rtPrintUnsigned (name, *pvalue);
}

/**************************************************************/
/*                                                            */
/*  ProcedureID_ddMode                                        */
/*                                                            */
/**************************************************************/

void asn1Print_ProcedureID_ddMode
   (const char* name, ProcedureID_ddMode* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("tdd\n"); break;
      case 1: printf ("fdd\n"); break;
      case 2: printf ("common_2\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

/**************************************************************/
/*                                                            */
/*  ProcedureID                                               */
/*                                                            */
/**************************************************************/

void asn1Print_ProcedureID
   (const char* name, ProcedureID* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.procedureCode", name);
   asn1Print_ProcedureCode (namebuf, &pvalue->procedureCode);

   sprintf (namebuf, "%s.ddMode", name);
   asn1Print_ProcedureID_ddMode (namebuf, &pvalue->ddMode);

}

/**************************************************************/
/*                                                            */
/*  Criticality                                               */
/*                                                            */
/**************************************************************/

void asn1Print_Criticality
   (const char* name, Criticality* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("reject\n"); break;
      case 1: printf ("ignore\n"); break;
      case 2: printf ("notify\n"); break;
      default: printf ("???\n");
   }
}

/**************************************************************/
/*                                                            */
/*  MessageDiscriminator                                      */
/*                                                            */
/**************************************************************/

void asn1Print_MessageDiscriminator
   (const char* name, MessageDiscriminator* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("common_1\n"); break;
      case 1: printf ("dedicated\n"); break;
      default: printf ("???\n");
   }
}

/**************************************************************/
/*                                                            */
/*  TransactionID                                             */
/*                                                            */
/**************************************************************/

void asn1Print_TransactionID
   (const char* name, TransactionID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t) {
      case 1:
         sprintf (namebuf, "%s.u.shortTransActionId", name);
         rtPrintUnsigned (namebuf, pvalue->u.shortTransActionId);
         break;

      case 2:
         sprintf (namebuf, "%s.u.longTransActionId", name);
         rtPrintUnsigned (namebuf, pvalue->u.longTransActionId);
         break;

      default:;
   }
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_ID                                             */
/*                                                            */
/**************************************************************/

void asn1Print_ProtocolIE_ID
   (const char* name, ProtocolIE_ID* pvalue)
{
   rtPrintUnsigned (name, *pvalue);
}

/**************************************************************/
/*                                                            */
/*  PrivateIE_ID                                              */
/*                                                            */
/**************************************************************/

void asn1Print_PrivateIE_ID
   (const char* name, PrivateIE_ID* pvalue)
{
   char namebuf[512];

   printf ("%s.t = %d\n", name, pvalue->t);
   switch (pvalue->t) {
      case 1:
         sprintf (namebuf, "%s.u.local", name);
         rtPrintUnsigned (namebuf, pvalue->u.local);
         break;

      case 2:
         sprintf (namebuf, "%s.u.global", name);
         rtPrintOID (namebuf, pvalue->u.global);
         break;

      default:;
   }
}

/**************************************************************/
/*                                                            */
/*  TriggeringMessage                                         */
/*                                                            */
/**************************************************************/

void asn1Print_TriggeringMessage
   (const char* name, TriggeringMessage* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("initiating_message\n"); break;
      case 1: printf ("successful_outcome\n"); break;
      case 2: printf ("unsuccessfull_outcome\n"); break;
      case 3: printf ("outcome\n"); break;
      default: printf ("???\n");
   }
}

/**************************************************************/
/*                                                            */
/*  Presence                                                  */
/*                                                            */
/**************************************************************/

void asn1Print_Presence
   (const char* name, Presence* pvalue)
{
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("optional\n"); break;
      case 1: printf ("conditional\n"); break;
      case 2: printf ("mandatory\n"); break;
      default: printf ("???\n");
   }
}

