/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 19-Mar-2007.
 */
#include "asn1intl.h"
#include "NBAP-PDU-Discriptions.h"
#include "NBAP-CommonDataTypes.h"
#include "NBAP-PDU-Contents.h"
#include "NBAP-IEs.h"
#include "NBAP-Constants.h"
#include "NBAP-Containers.h"

/**************************************************************/
/*                                                            */
/*  NBAP_PDU                                                  */
/*                                                            */
/**************************************************************/

NBAP_PDU* asn1Test_NBAP_PDU
   (ASN1CTXT* pctxt)
{
   NBAP_PDU* pvalue = (NBAP_PDU*)rtMemAllocZ (pctxt, sizeof(NBAP_PDU));
   memset((void*)pvalue, 0, sizeof(NBAP_PDU));

   /* Start Populating the choice type */
   pvalue->t =  T_NBAP_PDU_unsuccesfulOutcome;
   pvalue->u.unsuccesfulOutcome = (UnsuccessfulOutcome*)rtMemAllocZ(pctxt, sizeof(UnsuccessfulOutcome));
   /* Start populating the Sequence or Set type */

   /* Start populating the Sequence or Set type */

   /* Populate the Integer type */
   pvalue->u.unsuccesfulOutcome->procedureID.procedureCode = 4;

   /* Populate the Enumerated type */
   pvalue->u.unsuccesfulOutcome->procedureID.ddMode = tdd;
   /* End of Sequence or Set type */

   /* Populate the Enumerated type */
   pvalue->u.unsuccesfulOutcome->criticality = reject;

   /* Populate the Enumerated type */
   pvalue->u.unsuccesfulOutcome->messageDiscriminator = common_1;

   /* Start Populating the choice type */
   pvalue->u.unsuccesfulOutcome->transactionID.t =  T_TransactionID_shortTransActionId;
   /* Populate the Integer type */
   pvalue->u.unsuccesfulOutcome->transactionID.u.shortTransActionId = 119;
   /* End populating Choice type */

   /* Populate OpenType */
   /* Populate open type with encoded string
      - example uses arbitray string, users 
      should populate the encoded string of 
      appropriate type. The "-tables" option
      of compiler supports appropriate type 
      encoded string generation. */
   {
      static const OSOCTET testdata[] = {0x04, 0x08, 
      0x3d, 0x1f, 0xca, 0x34, 0xd0, 0x3f, 0x7e, 0xf6,  };
      pvalue->u.unsuccesfulOutcome->value.data = (ASN1ConstOctetPtr)rtMemAllocZ(pctxt, 10);
      pvalue->u.unsuccesfulOutcome->value.numocts = 10;
      memcpy ((void*)pvalue->u.unsuccesfulOutcome->value.data, testdata, 10);
   }
   /* End of Sequence or Set type */
   /* End populating Choice type */
   return (pvalue);
}

