/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 19-Mar-2007.
 */
#include "asn1intl.h"
#include "NBAP-CommonDataTypes.h"

/**************************************************************/
/*                                                            */
/*  ProcedureCode                                             */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProcedureCode (ASN1CTXT* pctxt, ProcedureCode* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProcedureCode: start\n");

   stat = pd_ConsUInt8 (pctxt, pvalue, OSUINTCONST(0), OSUINTCONST(255));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt,"asn1PD_ProcedureCode: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProcedureID_ddMode                                        */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProcedureID_ddMode (ASN1CTXT* pctxt, ProcedureID_ddMode* pvalue)
{
   int stat = 0;
   OSUINT32 ui;
   OSBOOL extbit;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProcedureID_ddMode: start\n");

   /* extension bit */

   PU_NEWFIELD (pctxt, "extension marker");

   stat = PD_BIT (pctxt, &extbit);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_SETBITCOUNT (pctxt);

   if (extbit) {
      PU_NEWFIELD (pctxt, "extension value");

      stat = pd_SmallNonNegWholeNumber (pctxt, &ui);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

      PU_SETBITCOUNT (pctxt);

      *pvalue = ui;
   }
   else {
      stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(2));
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

      switch (ui) {
         case 0: *pvalue = tdd; break;
         case 1: *pvalue = fdd; break;
         case 2: *pvalue = common_2; break;
         default: return LOG_ASN1ERR (pctxt, ASN_E_INVENUM);
      }
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_ProcedureID_ddMode: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProcedureID                                               */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProcedureID (ASN1CTXT* pctxt, ProcedureID* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProcedureID: start\n");

   /* decode procedureCode */

   PU_PUSHNAME (pctxt, "procedureCode");

   stat = asn1PD_ProcedureCode (pctxt, &pvalue->procedureCode);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode ddMode */

   PU_PUSHNAME (pctxt, "ddMode");

   stat = asn1PD_ProcedureID_ddMode (pctxt, &pvalue->ddMode);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   RTDIAGSTRM2 (pctxt,"asn1PD_ProcedureID: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  Criticality                                               */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_Criticality (ASN1CTXT* pctxt, Criticality* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt,"asn1PD_Criticality: start\n");

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   switch (ui) {
      case 0: *pvalue = reject; break;
      case 1: *pvalue = ignore; break;
      case 2: *pvalue = notify; break;
      default: return LOG_ASN1ERR (pctxt, ASN_E_INVENUM);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_Criticality: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  MessageDiscriminator                                      */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_MessageDiscriminator (ASN1CTXT* pctxt, MessageDiscriminator* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt,"asn1PD_MessageDiscriminator: start\n");

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(1));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   switch (ui) {
      case 0: *pvalue = common_1; break;
      case 1: *pvalue = dedicated; break;
      default: return LOG_ASN1ERR (pctxt, ASN_E_INVENUM);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_MessageDiscriminator: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  TransactionID                                             */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_TransactionID (ASN1CTXT* pctxt, TransactionID* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt,"asn1PD_TransactionID: start\n");

   PU_PUSHNAME (pctxt, "t");

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(1));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
   else pvalue->t = ui + 1;

   PU_POPNAME (pctxt);

   switch (ui) {
      /* shortTransActionId */
      case 0:
         PU_PUSHNAME (pctxt, "u.shortTransActionId");

         stat = pd_ConsUInt8 (pctxt, &pvalue->u.shortTransActionId, OSUINTCONST(0), OSUINTCONST(127));
         if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

         PU_POPNAME (pctxt);

         break;

      /* longTransActionId */
      case 1:
         PU_PUSHNAME (pctxt, "u.longTransActionId");

         stat = pd_ConsUInt16 (pctxt, &pvalue->u.longTransActionId, OSUINTCONST(0), OSUINTCONST(32767));
         if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

         PU_POPNAME (pctxt);

         break;

      default:
         return LOG_ASN1ERR (pctxt, ASN_E_INVOPT);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_TransactionID: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_ID                                             */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProtocolIE_ID (ASN1CTXT* pctxt, ProtocolIE_ID* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_ID: start\n");

   stat = pd_ConsUInt16 (pctxt, pvalue, OSUINTCONST(0), OSUINTCONST(65535));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_ID: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  PrivateIE_ID                                              */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_PrivateIE_ID (ASN1CTXT* pctxt, PrivateIE_ID* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt,"asn1PD_PrivateIE_ID: start\n");

   PU_PUSHNAME (pctxt, "t");

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(1));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
   else pvalue->t = ui + 1;

   PU_POPNAME (pctxt);

   switch (ui) {
      /* local */
      case 0:
         PU_PUSHNAME (pctxt, "u.local");

         stat = pd_ConsUInt16 (pctxt, &pvalue->u.local, OSUINTCONST(0), OSUINTCONST(65535));
         if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

         PU_POPNAME (pctxt);

         break;

      /* global */
      case 1:
         PU_PUSHNAME (pctxt, "u.global");

         pvalue->u.global = rtMemAllocTypeZ (pctxt, ASN1OBJID);
         if (pvalue->u.global == NULL)
            return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

         stat = pd_ObjectIdentifier (pctxt, pvalue->u.global);
         if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

         PU_POPNAME (pctxt);

         break;

      default:
         return LOG_ASN1ERR (pctxt, ASN_E_INVOPT);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_PrivateIE_ID: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  TriggeringMessage                                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_TriggeringMessage (ASN1CTXT* pctxt, TriggeringMessage* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt,"asn1PD_TriggeringMessage: start\n");

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(3));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   switch (ui) {
      case 0: *pvalue = initiating_message; break;
      case 1: *pvalue = successful_outcome; break;
      case 2: *pvalue = unsuccessfull_outcome; break;
      case 3: *pvalue = outcome; break;
      default: return LOG_ASN1ERR (pctxt, ASN_E_INVENUM);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_TriggeringMessage: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  Presence                                                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_Presence (ASN1CTXT* pctxt, Presence* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt,"asn1PD_Presence: start\n");

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   switch (ui) {
      case 0: *pvalue = optional; break;
      case 1: *pvalue = conditional; break;
      case 2: *pvalue = mandatory; break;
      default: return LOG_ASN1ERR (pctxt, ASN_E_INVENUM);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_Presence: end\n");

   return (stat);
}

