/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 19-Mar-2007.
 */
#include "asn1intl.h"
#include "NBAP-Containers.h"

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Field                                          */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProtocolIE_Field (ASN1CTXT* pctxt, ProtocolIE_Field* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_Field: start\n");

   /* decode id */

   PU_PUSHNAME (pctxt, "id");

   stat = asn1PD_ProtocolIE_ID (pctxt, &pvalue->id);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode criticality */

   PU_PUSHNAME (pctxt, "criticality");

   stat = asn1PD_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode value */

   PU_PUSHNAME (pctxt, "value");

   stat = pd_OpenType (pctxt, &pvalue->value.data, &pvalue->value.numocts);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_Field: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Single_Container                               */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProtocolIE_Single_Container (ASN1CTXT* pctxt, ProtocolIE_Single_Container* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_Single_Container: start\n");

   stat = asn1PD_ProtocolIE_Field (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_Single_Container: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Container                                      */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProtocolIE_Container (ASN1CTXT* pctxt, ProtocolIE_Container* pvalue)
{
   static Asn1SizeCnst lsize1 = { 0, OSUINTCONST(0), OSUINTCONST(65535), 0 };
   int stat = 0;
   ProtocolIE_Field* pdata;
   OSUINT32 count = 0;
   OSUINT32 xx1;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_Container: start\n");

   /* decode length determinant */

   PU_PUSHNAME (pctxt, "count");

   stat = pu_addSizeConstraint (pctxt, &lsize1);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   stat = pd_Length (pctxt, &count);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode elements */

   rtDListInit (pvalue);

   for (xx1 = 0; xx1 < count; xx1++) {
      PU_PUSHELEMNAME (pctxt, xx1);

      pdata = ALLOC_ASN1ELEMDNODE (pctxt, ProtocolIE_Field);
      if (pdata == NULL)
         return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

      stat = asn1PD_ProtocolIE_Field (pctxt, pdata);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

      PU_POPNAME (pctxt);
      rtDListAppendNode (pctxt, pvalue, pdata);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_Container: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionField                                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProtocolExtensionField (ASN1CTXT* pctxt, ProtocolExtensionField* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolExtensionField: start\n");

   /* decode id */

   PU_PUSHNAME (pctxt, "id");

   stat = asn1PD_ProtocolIE_ID (pctxt, &pvalue->id);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode criticality */

   PU_PUSHNAME (pctxt, "criticality");

   stat = asn1PD_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode extensionValue */

   PU_PUSHNAME (pctxt, "extensionValue");

   stat = pd_OpenType (pctxt, &pvalue->extensionValue.data, &pvalue->extensionValue.numocts);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolExtensionField: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionContainer                                */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProtocolExtensionContainer (ASN1CTXT* pctxt, ProtocolExtensionContainer* pvalue)
{
   static Asn1SizeCnst lsize1 = { 0, OSUINTCONST(1), OSUINTCONST(65535), 0 };
   int stat = 0;
   ProtocolExtensionField* pdata;
   OSUINT32 count = 0;
   OSUINT32 xx1;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolExtensionContainer: start\n");

   /* decode length determinant */

   PU_PUSHNAME (pctxt, "count");

   stat = pu_addSizeConstraint (pctxt, &lsize1);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   stat = pd_Length (pctxt, &count);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode elements */

   rtDListInit (pvalue);

   for (xx1 = 0; xx1 < count; xx1++) {
      PU_PUSHELEMNAME (pctxt, xx1);

      pdata = ALLOC_ASN1ELEMDNODE (pctxt, ProtocolExtensionField);
      if (pdata == NULL)
         return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

      stat = asn1PD_ProtocolExtensionField (pctxt, pdata);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

      PU_POPNAME (pctxt);
      rtDListAppendNode (pctxt, pvalue, pdata);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolExtensionContainer: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  PrivateIE_Field                                           */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_PrivateIE_Field (ASN1CTXT* pctxt, PrivateIE_Field* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_PrivateIE_Field: start\n");

   /* decode id */

   PU_PUSHNAME (pctxt, "id");

   stat = asn1PD_PrivateIE_ID (pctxt, &pvalue->id);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode criticality */

   PU_PUSHNAME (pctxt, "criticality");

   stat = asn1PD_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode value */

   PU_PUSHNAME (pctxt, "value");

   stat = pd_OpenType (pctxt, &pvalue->value.data, &pvalue->value.numocts);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   RTDIAGSTRM2 (pctxt,"asn1PD_PrivateIE_Field: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  PrivateIE_Container                                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_PrivateIE_Container (ASN1CTXT* pctxt, PrivateIE_Container* pvalue)
{
   static Asn1SizeCnst lsize1 = { 0, OSUINTCONST(1), OSUINTCONST(65535), 0 };
   int stat = 0;
   PrivateIE_Field* pdata;
   OSUINT32 count = 0;
   OSUINT32 xx1;

   RTDIAGSTRM2 (pctxt,"asn1PD_PrivateIE_Container: start\n");

   /* decode length determinant */

   PU_PUSHNAME (pctxt, "count");

   stat = pu_addSizeConstraint (pctxt, &lsize1);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   stat = pd_Length (pctxt, &count);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode elements */

   rtDListInit (pvalue);

   for (xx1 = 0; xx1 < count; xx1++) {
      PU_PUSHELEMNAME (pctxt, xx1);

      pdata = ALLOC_ASN1ELEMDNODE (pctxt, PrivateIE_Field);
      if (pdata == NULL)
         return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

      stat = asn1PD_PrivateIE_Field (pctxt, pdata);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

      PU_POPNAME (pctxt);
      rtDListAppendNode (pctxt, pvalue, pdata);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_PrivateIE_Container: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_FieldPair                                      */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProtocolIE_FieldPair (ASN1CTXT* pctxt, ProtocolIE_FieldPair* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_FieldPair: start\n");

   /* decode id */

   PU_PUSHNAME (pctxt, "id");

   stat = asn1PD_ProtocolIE_ID (pctxt, &pvalue->id);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode firstCriticality */

   PU_PUSHNAME (pctxt, "firstCriticality");

   stat = asn1PD_Criticality (pctxt, &pvalue->firstCriticality);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode firstValue */

   PU_PUSHNAME (pctxt, "firstValue");

   stat = pd_OpenType (pctxt, &pvalue->firstValue.data, &pvalue->firstValue.numocts);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode secondCriticality */

   PU_PUSHNAME (pctxt, "secondCriticality");

   stat = asn1PD_Criticality (pctxt, &pvalue->secondCriticality);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode secondValue */

   PU_PUSHNAME (pctxt, "secondValue");

   stat = pd_OpenType (pctxt, &pvalue->secondValue.data, &pvalue->secondValue.numocts);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_FieldPair: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_ContainerPair                                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_ProtocolIE_ContainerPair (ASN1CTXT* pctxt, ProtocolIE_ContainerPair* pvalue)
{
   static Asn1SizeCnst lsize1 = { 0, OSUINTCONST(0), OSUINTCONST(65535), 0 };
   int stat = 0;
   ProtocolIE_FieldPair* pdata;
   OSUINT32 count = 0;
   OSUINT32 xx1;

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_ContainerPair: start\n");

   /* decode length determinant */

   PU_PUSHNAME (pctxt, "count");

   stat = pu_addSizeConstraint (pctxt, &lsize1);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   stat = pd_Length (pctxt, &count);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* decode elements */

   rtDListInit (pvalue);

   for (xx1 = 0; xx1 < count; xx1++) {
      PU_PUSHELEMNAME (pctxt, xx1);

      pdata = ALLOC_ASN1ELEMDNODE (pctxt, ProtocolIE_FieldPair);
      if (pdata == NULL)
         return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

      stat = asn1PD_ProtocolIE_FieldPair (pctxt, pdata);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

      PU_POPNAME (pctxt);
      rtDListAppendNode (pctxt, pvalue, pdata);
   }

   RTDIAGSTRM2 (pctxt,"asn1PD_ProtocolIE_ContainerPair: end\n");

   return (stat);
}

