/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 19-Mar-2007.
 */
#include "asn1intl.h"
#include "NBAP-Containers.h"
#include "rtPrint.h"

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Field                                          */
/*                                                            */
/**************************************************************/

void asn1Print_ProtocolIE_Field
   (const char* name, ProtocolIE_Field* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.id", name);
   asn1Print_ProtocolIE_ID (namebuf, &pvalue->id);

   sprintf (namebuf, "%s.criticality", name);
   asn1Print_Criticality (namebuf, &pvalue->criticality);

   sprintf (namebuf, "%s.value", name);
   rtPrintOpenType (namebuf,
      pvalue->value.numocts,
      pvalue->value.data, ".");

}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Single_Container                               */
/*                                                            */
/**************************************************************/

void asn1Print_ProtocolIE_Single_Container
   (const char* name, ProtocolIE_Single_Container* pvalue)
{
   asn1Print_ProtocolIE_Field (name, pvalue);
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Container                                      */
/*                                                            */
/**************************************************************/

void asn1Print_ProtocolIE_Container
   (const char* name, ProtocolIE_Container* pvalue)
{
   ProtocolIE_Field* pdata;
   Asn1RTDListNode* pnode;
   char namebuf[512];

   printf ("%s.count = %d\n", name, pvalue->count);
   {
   OSUINT32 xx1;

   pnode = pvalue->head;
   for (xx1 = 0; xx1 < pvalue->count; xx1++) {
      pdata = (ProtocolIE_Field*) pnode->data;
      sprintf (namebuf, "%s.elem[%d]", name, xx1);
      asn1Print_ProtocolIE_Field (namebuf, pdata);
      pnode = pnode->next;
   }
   }
}

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionField                                    */
/*                                                            */
/**************************************************************/

void asn1Print_ProtocolExtensionField
   (const char* name, ProtocolExtensionField* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.id", name);
   asn1Print_ProtocolIE_ID (namebuf, &pvalue->id);

   sprintf (namebuf, "%s.criticality", name);
   asn1Print_Criticality (namebuf, &pvalue->criticality);

   sprintf (namebuf, "%s.extensionValue", name);
   rtPrintOpenType (namebuf,
      pvalue->extensionValue.numocts,
      pvalue->extensionValue.data, ".");

}

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionContainer                                */
/*                                                            */
/**************************************************************/

void asn1Print_ProtocolExtensionContainer
   (const char* name, ProtocolExtensionContainer* pvalue)
{
   ProtocolExtensionField* pdata;
   Asn1RTDListNode* pnode;
   char namebuf[512];

   printf ("%s.count = %d\n", name, pvalue->count);
   {
   OSUINT32 xx1;

   pnode = pvalue->head;
   for (xx1 = 0; xx1 < pvalue->count; xx1++) {
      pdata = (ProtocolExtensionField*) pnode->data;
      sprintf (namebuf, "%s.elem[%d]", name, xx1);
      asn1Print_ProtocolExtensionField (namebuf, pdata);
      pnode = pnode->next;
   }
   }
}

/**************************************************************/
/*                                                            */
/*  PrivateIE_Field                                           */
/*                                                            */
/**************************************************************/

void asn1Print_PrivateIE_Field
   (const char* name, PrivateIE_Field* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.id", name);
   asn1Print_PrivateIE_ID (namebuf, &pvalue->id);

   sprintf (namebuf, "%s.criticality", name);
   asn1Print_Criticality (namebuf, &pvalue->criticality);

   sprintf (namebuf, "%s.value", name);
   rtPrintOpenType (namebuf,
      pvalue->value.numocts,
      pvalue->value.data, ".");

}

/**************************************************************/
/*                                                            */
/*  PrivateIE_Container                                       */
/*                                                            */
/**************************************************************/

void asn1Print_PrivateIE_Container
   (const char* name, PrivateIE_Container* pvalue)
{
   PrivateIE_Field* pdata;
   Asn1RTDListNode* pnode;
   char namebuf[512];

   printf ("%s.count = %d\n", name, pvalue->count);
   {
   OSUINT32 xx1;

   pnode = pvalue->head;
   for (xx1 = 0; xx1 < pvalue->count; xx1++) {
      pdata = (PrivateIE_Field*) pnode->data;
      sprintf (namebuf, "%s.elem[%d]", name, xx1);
      asn1Print_PrivateIE_Field (namebuf, pdata);
      pnode = pnode->next;
   }
   }
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_FieldPair                                      */
/*                                                            */
/**************************************************************/

void asn1Print_ProtocolIE_FieldPair
   (const char* name, ProtocolIE_FieldPair* pvalue)
{
   char namebuf[512];

   sprintf (namebuf, "%s.id", name);
   asn1Print_ProtocolIE_ID (namebuf, &pvalue->id);

   sprintf (namebuf, "%s.firstCriticality", name);
   asn1Print_Criticality (namebuf, &pvalue->firstCriticality);

   sprintf (namebuf, "%s.firstValue", name);
   rtPrintOpenType (namebuf,
      pvalue->firstValue.numocts,
      pvalue->firstValue.data, ".");

   sprintf (namebuf, "%s.secondCriticality", name);
   asn1Print_Criticality (namebuf, &pvalue->secondCriticality);

   sprintf (namebuf, "%s.secondValue", name);
   rtPrintOpenType (namebuf,
      pvalue->secondValue.numocts,
      pvalue->secondValue.data, ".");

}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_ContainerPair                                  */
/*                                                            */
/**************************************************************/

void asn1Print_ProtocolIE_ContainerPair
   (const char* name, ProtocolIE_ContainerPair* pvalue)
{
   ProtocolIE_FieldPair* pdata;
   Asn1RTDListNode* pnode;
   char namebuf[512];

   printf ("%s.count = %d\n", name, pvalue->count);
   {
   OSUINT32 xx1;

   pnode = pvalue->head;
   for (xx1 = 0; xx1 < pvalue->count; xx1++) {
      pdata = (ProtocolIE_FieldPair*) pnode->data;
      sprintf (namebuf, "%s.elem[%d]", name, xx1);
      asn1Print_ProtocolIE_FieldPair (namebuf, pdata);
      pnode = pnode->next;
   }
   }
}

