/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 19-Mar-2007.
 */
#include "asn1intl.h"
#include "NBAP-CommonDataTypes.h"

/**************************************************************/
/*                                                            */
/*  ProcedureCode                                             */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_ProcedureCode (ASN1CTXT* pctxt, ProcedureCode value)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureCode: start\n");

   stat = pe_ConsUnsigned (pctxt, value, OSUINTCONST(0), OSUINTCONST(255));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureCode: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProcedureID_ddMode                                        */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_ProcedureID_ddMode (ASN1CTXT* pctxt, ProcedureID_ddMode value)
{
   int stat = 0;
   OSUINT32 ui;
   OSBOOL extbit;

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureID_ddMode: start\n");

   extbit = 0;

   switch (value) {
      case tdd: ui = 0; break;
      case fdd: ui = 1; break;
      case common_2: ui = 2; break;
      default: ui = value; extbit = 1;
   }

   /* extension bit */

   PU_NEWFIELD (pctxt, "extension marker");

   stat = pe_bit (pctxt, extbit);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_SETBITCOUNT (pctxt);

   if (extbit) {
      PU_NEWFIELD (pctxt, "extension value");

      stat = pe_SmallNonNegWholeNumber (pctxt, ui);

      PU_SETBITCOUNT (pctxt);
   }
   else {
      stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(2));
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
   }

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureID_ddMode: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProcedureID                                               */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_ProcedureID (ASN1CTXT* pctxt, ProcedureID* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureID: start\n");

   /* encode procedureCode */

   PU_PUSHNAME (pctxt, "procedureCode");

   stat = asn1PE_ProcedureCode (pctxt, pvalue->procedureCode);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
   PU_POPNAME (pctxt);

   /* encode ddMode */

   PU_PUSHNAME (pctxt, "ddMode");

   stat = asn1PE_ProcedureID_ddMode (pctxt, pvalue->ddMode);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
   PU_POPNAME (pctxt);

   RTDIAGSTRM2 (pctxt, "asn1PE_ProcedureID: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  Criticality                                               */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_Criticality (ASN1CTXT* pctxt, Criticality value)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt, "asn1PE_Criticality: start\n");

   switch (value) {
      case reject: ui = 0; break;
      case ignore: ui = 1; break;
      case notify: ui = 2; break;
      default: rtErrAddIntParm (&pctxt->errInfo, value);
      return LOG_ASN1ERR (pctxt, ASN_E_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_Criticality: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  MessageDiscriminator                                      */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_MessageDiscriminator (ASN1CTXT* pctxt, MessageDiscriminator value)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt, "asn1PE_MessageDiscriminator: start\n");

   switch (value) {
      case common_1: ui = 0; break;
      case dedicated: ui = 1; break;
      default: rtErrAddIntParm (&pctxt->errInfo, value);
      return LOG_ASN1ERR (pctxt, ASN_E_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(1));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_MessageDiscriminator: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  TransactionID                                             */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_TransactionID (ASN1CTXT* pctxt, TransactionID* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt, "asn1PE_TransactionID: start\n");

   /* Encode choice index value */

   PU_PUSHNAME (pctxt, "t");

   stat = pe_ConsUnsigned (pctxt, pvalue->t - 1, 0, 1);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* Encode root element data value */

   switch (pvalue->t)
   {
      /* shortTransActionId */
      case 1:
         PU_PUSHNAME (pctxt, "u.shortTransActionId");

         if ( (pvalue->u.shortTransActionId <= 127) ) {
            stat = pe_ConsUnsigned (pctxt, pvalue->u.shortTransActionId, OSUINTCONST(0), OSUINTCONST(127));
            if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
         }
         else
            return LOG_ASN1ERR (pctxt, ASN_E_CONSVIO);

         PU_POPNAME (pctxt);

         break;

      /* longTransActionId */
      case 2:
         PU_PUSHNAME (pctxt, "u.longTransActionId");

         if ( (pvalue->u.longTransActionId <= 32767) ) {
            stat = pe_ConsUnsigned (pctxt, pvalue->u.longTransActionId, OSUINTCONST(0), OSUINTCONST(32767));
            if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
         }
         else
            return LOG_ASN1ERR (pctxt, ASN_E_CONSVIO);

         PU_POPNAME (pctxt);

         break;

      default:
         return LOG_ASN1ERR (pctxt, ASN_E_INVOPT);
   }

   RTDIAGSTRM2 (pctxt, "asn1PE_TransactionID: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  ProtocolIE_ID                                             */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_ProtocolIE_ID (ASN1CTXT* pctxt, ProtocolIE_ID value)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt, "asn1PE_ProtocolIE_ID: start\n");

   stat = pe_ConsUnsigned (pctxt, value, OSUINTCONST(0), OSUINTCONST(65535));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_ProtocolIE_ID: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  PrivateIE_ID                                              */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_PrivateIE_ID (ASN1CTXT* pctxt, PrivateIE_ID* pvalue)
{
   int stat = 0;

   RTDIAGSTRM2 (pctxt, "asn1PE_PrivateIE_ID: start\n");

   /* Encode choice index value */

   PU_PUSHNAME (pctxt, "t");

   stat = pe_ConsUnsigned (pctxt, pvalue->t - 1, 0, 1);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   PU_POPNAME (pctxt);

   /* Encode root element data value */

   switch (pvalue->t)
   {
      /* local */
      case 1:
         PU_PUSHNAME (pctxt, "u.local");

         stat = pe_ConsUnsigned (pctxt, pvalue->u.local, OSUINTCONST(0), OSUINTCONST(65535));
         if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

         PU_POPNAME (pctxt);

         break;

      /* global */
      case 2:
         PU_PUSHNAME (pctxt, "u.global");

         stat = pe_ObjectIdentifier (pctxt, pvalue->u.global);
         if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
         PU_POPNAME (pctxt);

         break;

      default:
         return LOG_ASN1ERR (pctxt, ASN_E_INVOPT);
   }

   RTDIAGSTRM2 (pctxt, "asn1PE_PrivateIE_ID: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  TriggeringMessage                                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_TriggeringMessage (ASN1CTXT* pctxt, TriggeringMessage value)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt, "asn1PE_TriggeringMessage: start\n");

   switch (value) {
      case initiating_message: ui = 0; break;
      case successful_outcome: ui = 1; break;
      case unsuccessfull_outcome: ui = 2; break;
      case outcome: ui = 3; break;
      default: rtErrAddIntParm (&pctxt->errInfo, value);
      return LOG_ASN1ERR (pctxt, ASN_E_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(3));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_TriggeringMessage: end\n");

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  Presence                                                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PE_Presence (ASN1CTXT* pctxt, Presence value)
{
   int stat = 0;
   OSUINT32 ui;

   RTDIAGSTRM2 (pctxt, "asn1PE_Presence: start\n");

   switch (value) {
      case optional: ui = 0; break;
      case conditional: ui = 1; break;
      case mandatory: ui = 2; break;
      default: rtErrAddIntParm (&pctxt->errInfo, value);
      return LOG_ASN1ERR (pctxt, ASN_E_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   RTDIAGSTRM2 (pctxt, "asn1PE_Presence: end\n");

   return (stat);
}

