/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 19-Mar-2007.
 */
#ifndef NBAP_CONTAINERS_H
#define NBAP_CONTAINERS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1per.h"
#include "NBAP-CommonDataTypes.h"

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Field                                          */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ProtocolIE_Field {
   ProtocolIE_ID id;
   Criticality criticality;
   ASN1OpenType value;
} ProtocolIE_Field;

EXTERN int asn1PE_ProtocolIE_Field (ASN1CTXT* pctxt, ProtocolIE_Field* pvalue);

EXTERN int asn1PD_ProtocolIE_Field (ASN1CTXT* pctxt, ProtocolIE_Field* pvalue);

EXTERN void asn1Print_ProtocolIE_Field
   (const char* name, ProtocolIE_Field* pvalue);

EXTERN ProtocolIE_Field* asn1Test_ProtocolIE_Field
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Single_Container                               */
/*                                                            */
/**************************************************************/

typedef ProtocolIE_Field ProtocolIE_Single_Container;

EXTERN int asn1PE_ProtocolIE_Single_Container (ASN1CTXT* pctxt, ProtocolIE_Single_Container* pvalue);

EXTERN int asn1PD_ProtocolIE_Single_Container (ASN1CTXT* pctxt, ProtocolIE_Single_Container* pvalue);

EXTERN void asn1Print_ProtocolIE_Single_Container
   (const char* name, ProtocolIE_Single_Container* pvalue);

EXTERN ProtocolIE_Single_Container* asn1Test_ProtocolIE_Single_Container
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Container                                      */
/*                                                            */
/**************************************************************/

/* List of ProtocolIE_Field */
typedef Asn1RTDList ProtocolIE_Container;

EXTERN int asn1PE_ProtocolIE_Container (ASN1CTXT* pctxt, ProtocolIE_Container* pvalue);

EXTERN int asn1PD_ProtocolIE_Container (ASN1CTXT* pctxt, ProtocolIE_Container* pvalue);

EXTERN void asn1Print_ProtocolIE_Container
   (const char* name, ProtocolIE_Container* pvalue);

EXTERN ProtocolIE_Container* asn1Test_ProtocolIE_Container
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionField                                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ProtocolExtensionField {
   ProtocolIE_ID id;
   Criticality criticality;
   ASN1OpenType extensionValue;
} ProtocolExtensionField;

EXTERN int asn1PE_ProtocolExtensionField (ASN1CTXT* pctxt, ProtocolExtensionField* pvalue);

EXTERN int asn1PD_ProtocolExtensionField (ASN1CTXT* pctxt, ProtocolExtensionField* pvalue);

EXTERN void asn1Print_ProtocolExtensionField
   (const char* name, ProtocolExtensionField* pvalue);

EXTERN ProtocolExtensionField* asn1Test_ProtocolExtensionField
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionContainer                                */
/*                                                            */
/**************************************************************/

/* List of ProtocolExtensionField */
typedef Asn1RTDList ProtocolExtensionContainer;

EXTERN int asn1PE_ProtocolExtensionContainer (ASN1CTXT* pctxt, ProtocolExtensionContainer* pvalue);

EXTERN int asn1PD_ProtocolExtensionContainer (ASN1CTXT* pctxt, ProtocolExtensionContainer* pvalue);

EXTERN void asn1Print_ProtocolExtensionContainer
   (const char* name, ProtocolExtensionContainer* pvalue);

EXTERN ProtocolExtensionContainer* asn1Test_ProtocolExtensionContainer
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  PrivateIE_Field                                           */
/*                                                            */
/**************************************************************/

typedef struct EXTERN PrivateIE_Field {
   PrivateIE_ID id;
   Criticality criticality;
   ASN1OpenType value;
} PrivateIE_Field;

EXTERN int asn1PE_PrivateIE_Field (ASN1CTXT* pctxt, PrivateIE_Field* pvalue);

EXTERN int asn1PD_PrivateIE_Field (ASN1CTXT* pctxt, PrivateIE_Field* pvalue);

EXTERN void asn1Print_PrivateIE_Field
   (const char* name, PrivateIE_Field* pvalue);

EXTERN PrivateIE_Field* asn1Test_PrivateIE_Field
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  PrivateIE_Container                                       */
/*                                                            */
/**************************************************************/

/* List of PrivateIE_Field */
typedef Asn1RTDList PrivateIE_Container;

EXTERN int asn1PE_PrivateIE_Container (ASN1CTXT* pctxt, PrivateIE_Container* pvalue);

EXTERN int asn1PD_PrivateIE_Container (ASN1CTXT* pctxt, PrivateIE_Container* pvalue);

EXTERN void asn1Print_PrivateIE_Container
   (const char* name, PrivateIE_Container* pvalue);

EXTERN PrivateIE_Container* asn1Test_PrivateIE_Container
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  ProtocolIE_FieldPair                                      */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ProtocolIE_FieldPair {
   ProtocolIE_ID id;
   Criticality firstCriticality;
   ASN1OpenType firstValue;
   Criticality secondCriticality;
   ASN1OpenType secondValue;
} ProtocolIE_FieldPair;

EXTERN int asn1PE_ProtocolIE_FieldPair (ASN1CTXT* pctxt, ProtocolIE_FieldPair* pvalue);

EXTERN int asn1PD_ProtocolIE_FieldPair (ASN1CTXT* pctxt, ProtocolIE_FieldPair* pvalue);

EXTERN void asn1Print_ProtocolIE_FieldPair
   (const char* name, ProtocolIE_FieldPair* pvalue);

EXTERN ProtocolIE_FieldPair* asn1Test_ProtocolIE_FieldPair
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  ProtocolIE_ContainerPair                                  */
/*                                                            */
/**************************************************************/

/* List of ProtocolIE_FieldPair */
typedef Asn1RTDList ProtocolIE_ContainerPair;

EXTERN int asn1PE_ProtocolIE_ContainerPair (ASN1CTXT* pctxt, ProtocolIE_ContainerPair* pvalue);

EXTERN int asn1PD_ProtocolIE_ContainerPair (ASN1CTXT* pctxt, ProtocolIE_ContainerPair* pvalue);

EXTERN void asn1Print_ProtocolIE_ContainerPair
   (const char* name, ProtocolIE_ContainerPair* pvalue);

EXTERN ProtocolIE_ContainerPair* asn1Test_ProtocolIE_ContainerPair
   (ASN1CTXT* pctxt);

#ifdef __cplusplus
}
#endif

#endif
