/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#ifndef RANAP_PDU_DESCRIPTIONSCLASS_H
#define RANAP_PDU_DESCRIPTIONSCLASS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1per.h"
#include "rtTable.h"
#include "RANAP-PDU-Descriptions.h"
#include "RANAP-Constants.h"

/* Class definitions */

/**************************************************************/
/*                                                            */
/*  RANAP_ELEMENTARY_PROCEDURE                                */
/*                                                            */
/**************************************************************/

typedef struct RANAP_ELEMENTARY_PROCEDURE {
   struct {
      unsigned SuccessfulOutcomePresent : 1;
      unsigned UnsuccessfulOutcomePresent : 1;
      unsigned OutcomePresent : 1;
      unsigned criticalityPresent : 1;
   } m;
   int InitiatingMessageSize;
   int (*encodeInitiatingMessage) (ASN1CTXT* , void * );
   int (*decodeInitiatingMessage) (ASN1CTXT* , void * );
   void (*printInitiatingMessage) (ASN1ConstCharPtr , void * );
   int SuccessfulOutcomeSize;
   int (*encodeSuccessfulOutcome) (ASN1CTXT* , void * );
   int (*decodeSuccessfulOutcome) (ASN1CTXT* , void * );
   void (*printSuccessfulOutcome) (ASN1ConstCharPtr , void * );
   int UnsuccessfulOutcomeSize;
   int (*encodeUnsuccessfulOutcome) (ASN1CTXT* , void * );
   int (*decodeUnsuccessfulOutcome) (ASN1CTXT* , void * );
   void (*printUnsuccessfulOutcome) (ASN1ConstCharPtr , void * );
   int OutcomeSize;
   int (*encodeOutcome) (ASN1CTXT* , void * );
   int (*decodeOutcome) (ASN1CTXT* , void * );
   void (*printOutcome) (ASN1ConstCharPtr , void * );
   OSUINT8 procedureCode;
   OSUINT32 criticality;
} RANAP_ELEMENTARY_PROCEDURE;

#ifdef __cplusplus
}
#endif

#endif
