/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#include "asn1intl.h"
#include "RANAP-PDU-DescriptionsTable.h"
#include "RANAP-PDU-ContentsTable.h"
#include "RANAP-IEsTable.h"

/**************************************************************/
/*                                                            */
/*  RANAP_PDU                                                 */
/*                                                            */
/**************************************************************/

RANAP_PDU* asn1Test_RANAP_PDU
   (ASN1CTXT* pctxt)
{
   RANAP_PDU* pvalue = (RANAP_PDU*)rtMemAllocZ (pctxt, sizeof(RANAP_PDU));
   memset((void*)pvalue, 0, sizeof(RANAP_PDU));

   /* Start Populating the choice type */
   pvalue->t =  T_RANAP_PDU_extElem1;
   pvalue->u.extElem1 = (ASN1OpenType*)rtMemAllocZ(pctxt, sizeof(ASN1OpenType));
   /* Populate OpenType */
   /* End populating Choice type */
   return (pvalue);
}

