/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#ifndef RANAP_PDU_DESCRIPTIONSTABLE_H
#define RANAP_PDU_DESCRIPTIONSTABLE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1per.h"
#include "rtTable.h"
#include "RANAP-PDU-DescriptionsClass.h"
#include "RANAP-Constants.h"
#include "RANAP-ContainersClass.h"

/* Intialization function */
extern void RANAP_PDU_Descriptions_init(ASN1CTXT *pctxt);

/* Object definitions */

extern struct RANAP_ELEMENTARY_PROCEDURE iu_Release;
extern struct RANAP_ELEMENTARY_PROCEDURE relocationPreparation;
extern struct RANAP_ELEMENTARY_PROCEDURE relocationResourceAllocation;
extern struct RANAP_ELEMENTARY_PROCEDURE relocationCancel;
extern struct RANAP_ELEMENTARY_PROCEDURE sRNS_ContextTransfer;
extern struct RANAP_ELEMENTARY_PROCEDURE securityModeControl;
extern struct RANAP_ELEMENTARY_PROCEDURE dataVolumeReport;
extern struct RANAP_ELEMENTARY_PROCEDURE reset;
extern struct RANAP_ELEMENTARY_PROCEDURE rAB_ReleaseRequest;
extern struct RANAP_ELEMENTARY_PROCEDURE iu_ReleaseRequest;
extern struct RANAP_ELEMENTARY_PROCEDURE relocationDetect;
extern struct RANAP_ELEMENTARY_PROCEDURE relocationComplete;
extern struct RANAP_ELEMENTARY_PROCEDURE paging;
extern struct RANAP_ELEMENTARY_PROCEDURE commonID;
extern struct RANAP_ELEMENTARY_PROCEDURE cN_InvokeTrace;
extern struct RANAP_ELEMENTARY_PROCEDURE cN_DeactivateTrace;
extern struct RANAP_ELEMENTARY_PROCEDURE locationReportingControl;
extern struct RANAP_ELEMENTARY_PROCEDURE locationReport;
extern struct RANAP_ELEMENTARY_PROCEDURE initialUE_Message;
extern struct RANAP_ELEMENTARY_PROCEDURE directTransfer;
extern struct RANAP_ELEMENTARY_PROCEDURE overloadControl;
extern struct RANAP_ELEMENTARY_PROCEDURE errorIndication;
extern struct RANAP_ELEMENTARY_PROCEDURE sRNS_DataForward;
extern struct RANAP_ELEMENTARY_PROCEDURE forwardSRNS_Context;
extern struct RANAP_ELEMENTARY_PROCEDURE rAB_Assignment;
extern struct RANAP_ELEMENTARY_PROCEDURE privateMessage;
extern struct RANAP_ELEMENTARY_PROCEDURE resetResource;
extern struct RANAP_ELEMENTARY_PROCEDURE rANAP_Relocation;
extern struct RANAP_ELEMENTARY_PROCEDURE rAB_ModifyRequest;
extern struct RANAP_ELEMENTARY_PROCEDURE locationRelatedData;
extern struct RANAP_ELEMENTARY_PROCEDURE informationTransfer;
extern struct RANAP_ELEMENTARY_PROCEDURE uESpecificInformation;
extern struct RANAP_ELEMENTARY_PROCEDURE directInformationTransfer;
extern struct RANAP_ELEMENTARY_PROCEDURE uplinkInformationExchange;
extern struct RANAP_ELEMENTARY_PROCEDURE mBMSSessionStart;
extern struct RANAP_ELEMENTARY_PROCEDURE mBMSSessionUpdate;
extern struct RANAP_ELEMENTARY_PROCEDURE mBMSSessionStop;
extern struct RANAP_ELEMENTARY_PROCEDURE mBMSUELinking;
extern struct RANAP_ELEMENTARY_PROCEDURE mBMSRegistration;
extern struct RANAP_ELEMENTARY_PROCEDURE mBMSCNDe_Registration;
extern struct RANAP_ELEMENTARY_PROCEDURE mBMSRABEstablishmentIndication;
extern struct RANAP_ELEMENTARY_PROCEDURE mBMSRABRelease;
/* ObjectSet definitions */

extern struct RANAP_ELEMENTARY_PROCEDURE RANAP_ELEMENTARY_PROCEDURES[];
extern int RANAP_ELEMENTARY_PROCEDURES_Size;
extern struct RANAP_ELEMENTARY_PROCEDURE RANAP_ELEMENTARY_PROCEDURES_CLASS_1[];
extern int RANAP_ELEMENTARY_PROCEDURES_CLASS_1_Size;
extern struct RANAP_ELEMENTARY_PROCEDURE RANAP_ELEMENTARY_PROCEDURES_CLASS_2[];
extern int RANAP_ELEMENTARY_PROCEDURES_CLASS_2_Size;
extern struct RANAP_ELEMENTARY_PROCEDURE RANAP_ELEMENTARY_PROCEDURES_CLASS_3[];
extern int RANAP_ELEMENTARY_PROCEDURES_CLASS_3_Size;

#ifdef __cplusplus
}
#endif

#endif
