/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#include "asn1intl.h"
#include "RANAP-IEsTable.h"

/**************************************************************/
/*                                                            */
/*  RateControlAllowed                                        */
/*                                                            */
/**************************************************************/

RateControlAllowed* asn1Test_RateControlAllowed
   (ASN1CTXT* pctxt)
{
   RateControlAllowed* pvalue = (RateControlAllowed*)rtMemAllocZ (pctxt, sizeof(RateControlAllowed));
   memset((void*)pvalue, 0, sizeof(RateControlAllowed));

   /* Populate the Enumerated type */
   *pvalue = not_allowed;
   return (pvalue);
}

