/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#ifndef RANAP_COMMONDATATYPES_H
#define RANAP_COMMONDATATYPES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1per.h"
#include "rtTable.h"

/**************************************************************/
/*                                                            */
/*  ProtocolIE_ID                                             */
/*                                                            */
/**************************************************************/

typedef OSUINT16 ProtocolIE_ID;

EXTERN int asn1PE_ProtocolIE_ID (ASN1CTXT* pctxt, ProtocolIE_ID value);

EXTERN int asn1PD_ProtocolIE_ID (ASN1CTXT* pctxt, ProtocolIE_ID* pvalue);

EXTERN void asn1Print_ProtocolIE_ID
   (const char* name, ProtocolIE_ID* pvalue);

EXTERN ProtocolIE_ID* asn1Test_ProtocolIE_ID
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  Criticality                                               */
/*                                                            */
/**************************************************************/

typedef enum {
   reject = 0,
   ignore = 1,
   notify = 2
} Criticality_Root;

typedef OSUINT32 Criticality;

EXTERN int asn1PE_Criticality (ASN1CTXT* pctxt, Criticality value);

EXTERN int asn1PD_Criticality (ASN1CTXT* pctxt, Criticality* pvalue);

EXTERN void asn1Print_Criticality
   (const char* name, Criticality* pvalue);

EXTERN Criticality* asn1Test_Criticality
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  Presence                                                  */
/*                                                            */
/**************************************************************/

typedef enum {
   optional = 0,
   conditional = 1,
   mandatory = 2
} Presence_Root;

typedef OSUINT32 Presence;

EXTERN int asn1PE_Presence (ASN1CTXT* pctxt, Presence value);

EXTERN int asn1PD_Presence (ASN1CTXT* pctxt, Presence* pvalue);

EXTERN void asn1Print_Presence
   (const char* name, Presence* pvalue);

EXTERN Presence* asn1Test_Presence
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionID                                       */
/*                                                            */
/**************************************************************/

typedef OSUINT16 ProtocolExtensionID;

EXTERN int asn1PE_ProtocolExtensionID (ASN1CTXT* pctxt, ProtocolExtensionID value);

EXTERN int asn1PD_ProtocolExtensionID (ASN1CTXT* pctxt, ProtocolExtensionID* pvalue);

EXTERN void asn1Print_ProtocolExtensionID
   (const char* name, ProtocolExtensionID* pvalue);

EXTERN ProtocolExtensionID* asn1Test_ProtocolExtensionID
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  ProcedureCode                                             */
/*                                                            */
/**************************************************************/

typedef OSUINT8 ProcedureCode;

EXTERN int asn1PE_ProcedureCode (ASN1CTXT* pctxt, ProcedureCode value);

EXTERN int asn1PD_ProcedureCode (ASN1CTXT* pctxt, ProcedureCode* pvalue);

EXTERN void asn1Print_ProcedureCode
   (const char* name, ProcedureCode* pvalue);

EXTERN ProcedureCode* asn1Test_ProcedureCode
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  TriggeringMessage                                         */
/*                                                            */
/**************************************************************/

typedef enum {
   initiating_message = 0,
   successful_outcome = 1,
   unsuccessfull_outcome = 2,
   outcome = 3
} TriggeringMessage_Root;

typedef OSUINT32 TriggeringMessage;

EXTERN int asn1PE_TriggeringMessage (ASN1CTXT* pctxt, TriggeringMessage value);

EXTERN int asn1PD_TriggeringMessage (ASN1CTXT* pctxt, TriggeringMessage* pvalue);

EXTERN void asn1Print_TriggeringMessage
   (const char* name, TriggeringMessage* pvalue);

EXTERN TriggeringMessage* asn1Test_TriggeringMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  PrivateIE_ID                                              */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_PrivateIE_ID_local            1
#define T_PrivateIE_ID_global           2

typedef struct EXTERN PrivateIE_ID {
   int t;
   union {
      /* t = 1 */
      OSUINT16 local;
      /* t = 2 */
      ASN1OBJID *global;
   } u;
} PrivateIE_ID;

EXTERN int asn1PE_PrivateIE_ID (ASN1CTXT* pctxt, PrivateIE_ID* pvalue);

EXTERN int asn1PD_PrivateIE_ID (ASN1CTXT* pctxt, PrivateIE_ID* pvalue);

EXTERN void asn1Print_PrivateIE_ID
   (const char* name, PrivateIE_ID* pvalue);

EXTERN PrivateIE_ID* asn1Test_PrivateIE_ID
   (ASN1CTXT* pctxt);

EXTERN int asn1CmpTC_PrivateIE_ID (PrivateIE_ID* pValue, PrivateIE_ID* pCmpValue);

#ifdef __cplusplus
}
#endif

#endif
