/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#include <stdio.h>
#include <stdlib.h>
#include "RANAP-IEsTable.h"
#include "rtPrint.h"
#include "asn1intl.h"

extern void init_AllocationOrRetentionPriority_ExtIEs(ASN1CTXT *pctxt);
extern void init_Alt_RAB_Parameters_ExtIEs(ASN1CTXT *pctxt);
extern void init_Ass_RAB_Parameters_ExtIEs(ASN1CTXT *pctxt);
extern void init_AuthorisedPLMNs_ExtIEs(ASN1CTXT *pctxt);
extern void init_CellLoadInformation_ExtIEs(ASN1CTXT *pctxt);
extern void init_CellLoadInformationGroup_ExtIEs(ASN1CTXT *pctxt);
extern void init_CriticalityDiagnostics_ExtIEs(ASN1CTXT *pctxt);
extern void init_CriticalityDiagnostics_IE_List_ExtIEs(ASN1CTXT *pctxt);
extern void init_MessageStructure_ExtIEs(ASN1CTXT *pctxt);
extern void init_CGI_ExtIEs(ASN1CTXT *pctxt);
extern void init_DeltaRAListofIdleModeUEs_ExtIEs(ASN1CTXT *pctxt);
extern void init_EncryptionInformation_ExtIEs(ASN1CTXT *pctxt);
extern void init_GeographicalCoordinates_ExtIEs(ASN1CTXT *pctxt);
extern void init_GA_EllipsoidArc_ExtIEs(ASN1CTXT *pctxt);
extern void init_GA_Point_ExtIEs(ASN1CTXT *pctxt);
extern void init_GA_PointWithAltitude_ExtIEs(ASN1CTXT *pctxt);
extern void init_GA_PointWithAltitudeAndUncertaintyEllipsoid_ExtIEs(ASN1CTXT *pctxt);
extern void init_GA_PointWithUnCertainty_ExtIEs(ASN1CTXT *pctxt);
extern void init_GA_PointWithUnCertaintyEllipse_ExtIEs(ASN1CTXT *pctxt);
extern void init_GA_Polygon_ExtIEs(ASN1CTXT *pctxt);
extern void init_GERAN_Cell_ID_ExtIEs(ASN1CTXT *pctxt);
extern void init_IMEIGroup_ExtIEs(ASN1CTXT *pctxt);
extern void init_IMEISVGroup_ExtIEs(ASN1CTXT *pctxt);
extern void init_IntegrityProtectionInformation_ExtIEs(ASN1CTXT *pctxt);
extern void init_InterSystemInformation_TransparentContainer_ExtIEs(ASN1CTXT *pctxt);
extern void init_LA_LIST_ExtIEs(ASN1CTXT *pctxt);
extern void init_LAI_ExtIEs(ASN1CTXT *pctxt);
extern void init_LastKnownServiceArea_ExtIEs(ASN1CTXT *pctxt);
extern void init_InterfacesToTraceItem_ExtIEs(ASN1CTXT *pctxt);
extern void init_PLMNs_in_shared_network_ExtIEs(ASN1CTXT *pctxt);
extern void init_PositionData_ExtIEs(ASN1CTXT *pctxt);
extern void init_RAB_Parameters_ExtIEs(ASN1CTXT *pctxt);
extern void init_RAB_TrCH_MappingItem_ExtIEs(ASN1CTXT *pctxt);
extern void init_RAI_ExtIEs(ASN1CTXT *pctxt);
extern void init_NotEmptyRAListofIdleModeUEs_ExtIEs(ASN1CTXT *pctxt);
extern void init_MBMSIPMulticastAddressandAPNlist_ExtIEs(ASN1CTXT *pctxt);
extern void init_Requested_RAB_Parameter_Values_ExtIEs(ASN1CTXT *pctxt);
extern void init_ResidualBitErrorRatio_ExtIEs(ASN1CTXT *pctxt);
extern void init_RIM_Transfer_ExtIEs(ASN1CTXT *pctxt);
extern void init_RNCTraceInformation_ExtIEs(ASN1CTXT *pctxt);
extern void init_SAI_ExtIEs(ASN1CTXT *pctxt);
extern void init_Shared_Network_Information_ExtIEs(ASN1CTXT *pctxt);
extern void init_SDU_ErrorRatio_ExtIEs(ASN1CTXT *pctxt);
extern void init_SDU_FormatInformationParameters_ExtIEs(ASN1CTXT *pctxt);
extern void init_SDU_Parameters_ExtIEs(ASN1CTXT *pctxt);
extern void init_SNA_Access_Information_ExtIEs(ASN1CTXT *pctxt);
extern void init_SourceRNC_ID_ExtIEs(ASN1CTXT *pctxt);
extern void init_SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs(ASN1CTXT *pctxt);
extern void init_SourceUTRANCellID_ExtIEs(ASN1CTXT *pctxt);
extern void init_SRB_TrCH_MappingItem_ExtIEs(ASN1CTXT *pctxt);
extern void init_TargetRNC_ID_ExtIEs(ASN1CTXT *pctxt);
extern void init_TargetRNC_ToSourceRNC_TransparentContainer_ExtIEs(ASN1CTXT *pctxt);
extern void init_TMGI_ExtIEs(ASN1CTXT *pctxt);
extern void init_TracePropagationParameters_ExtIEs(ASN1CTXT *pctxt);
extern void init_TraceRecordingSessionInformation_ExtIEs(ASN1CTXT *pctxt);
extern void init_TrCH_ID_ExtIEs(ASN1CTXT *pctxt);
extern void init_UESBI_Iu_ExtIEs(ASN1CTXT *pctxt);

void RANAP_IEs_init(ASN1CTXT *pctxt)
{
   init_AllocationOrRetentionPriority_ExtIEs(pctxt);
   init_Alt_RAB_Parameters_ExtIEs(pctxt);
   init_Ass_RAB_Parameters_ExtIEs(pctxt);
   init_AuthorisedPLMNs_ExtIEs(pctxt);
   init_CellLoadInformation_ExtIEs(pctxt);
   init_CellLoadInformationGroup_ExtIEs(pctxt);
   init_CriticalityDiagnostics_ExtIEs(pctxt);
   init_CriticalityDiagnostics_IE_List_ExtIEs(pctxt);
   init_MessageStructure_ExtIEs(pctxt);
   init_CGI_ExtIEs(pctxt);
   init_DeltaRAListofIdleModeUEs_ExtIEs(pctxt);
   init_EncryptionInformation_ExtIEs(pctxt);
   init_GeographicalCoordinates_ExtIEs(pctxt);
   init_GA_EllipsoidArc_ExtIEs(pctxt);
   init_GA_Point_ExtIEs(pctxt);
   init_GA_PointWithAltitude_ExtIEs(pctxt);
   init_GA_PointWithAltitudeAndUncertaintyEllipsoid_ExtIEs(pctxt);
   init_GA_PointWithUnCertainty_ExtIEs(pctxt);
   init_GA_PointWithUnCertaintyEllipse_ExtIEs(pctxt);
   init_GA_Polygon_ExtIEs(pctxt);
   init_GERAN_Cell_ID_ExtIEs(pctxt);
   init_IMEIGroup_ExtIEs(pctxt);
   init_IMEISVGroup_ExtIEs(pctxt);
   init_IntegrityProtectionInformation_ExtIEs(pctxt);
   init_InterSystemInformation_TransparentContainer_ExtIEs(pctxt);
   init_LA_LIST_ExtIEs(pctxt);
   init_LAI_ExtIEs(pctxt);
   init_LastKnownServiceArea_ExtIEs(pctxt);
   init_InterfacesToTraceItem_ExtIEs(pctxt);
   init_PLMNs_in_shared_network_ExtIEs(pctxt);
   init_PositionData_ExtIEs(pctxt);
   init_RAB_Parameters_ExtIEs(pctxt);
   init_RAB_TrCH_MappingItem_ExtIEs(pctxt);
   init_RAI_ExtIEs(pctxt);
   init_NotEmptyRAListofIdleModeUEs_ExtIEs(pctxt);
   init_MBMSIPMulticastAddressandAPNlist_ExtIEs(pctxt);
   init_Requested_RAB_Parameter_Values_ExtIEs(pctxt);
   init_ResidualBitErrorRatio_ExtIEs(pctxt);
   init_RIM_Transfer_ExtIEs(pctxt);
   init_RNCTraceInformation_ExtIEs(pctxt);
   init_SAI_ExtIEs(pctxt);
   init_Shared_Network_Information_ExtIEs(pctxt);
   init_SDU_ErrorRatio_ExtIEs(pctxt);
   init_SDU_FormatInformationParameters_ExtIEs(pctxt);
   init_SDU_Parameters_ExtIEs(pctxt);
   init_SNA_Access_Information_ExtIEs(pctxt);
   init_SourceRNC_ID_ExtIEs(pctxt);
   init_SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs(pctxt);
   init_SourceUTRANCellID_ExtIEs(pctxt);
   init_SRB_TrCH_MappingItem_ExtIEs(pctxt);
   init_TargetRNC_ID_ExtIEs(pctxt);
   init_TargetRNC_ToSourceRNC_TransparentContainer_ExtIEs(pctxt);
   init_TMGI_ExtIEs(pctxt);
   init_TracePropagationParameters_ExtIEs(pctxt);
   init_TraceRecordingSessionInformation_ExtIEs(pctxt);
   init_TrCH_ID_ExtIEs(pctxt);
   init_UESBI_Iu_ExtIEs(pctxt);
}

/**************************************************************/
/*                                                            */
/*  AllocationOrRetentionPriority_ExtIEs                      */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION AllocationOrRetentionPriority_ExtIEs[1];
int AllocationOrRetentionPriority_ExtIEs_Size = 0;

void init_AllocationOrRetentionPriority_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  Alt_RAB_Parameters_ExtIEs                                 */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION Alt_RAB_Parameters_ExtIEs[1];
int Alt_RAB_Parameters_ExtIEs_Size = 1;

void init_Alt_RAB_Parameters_ExtIEs(ASN1CTXT *pctxt)
{

   Alt_RAB_Parameters_ExtIEs[0].id = 158;
   Alt_RAB_Parameters_ExtIEs[0].criticality = ignore;
   Alt_RAB_Parameters_ExtIEs[0].ExtensionSize = sizeof(_Alt_RAB_Parameters_ExtIEs_Extension);
   Alt_RAB_Parameters_ExtIEs[0].encodeExtension = &asn1PE__Alt_RAB_Parameters_ExtIEs_Extension;
   Alt_RAB_Parameters_ExtIEs[0].decodeExtension = &asn1PD__Alt_RAB_Parameters_ExtIEs_Extension;
   Alt_RAB_Parameters_ExtIEs[0].printExtension = &asn1Print__Alt_RAB_Parameters_ExtIEs_Extension;
   Alt_RAB_Parameters_ExtIEs[0].presence = optional;

}

/**************************************************************/
/*                                                            */
/*  Ass_RAB_Parameters_ExtIEs                                 */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION Ass_RAB_Parameters_ExtIEs[1];
int Ass_RAB_Parameters_ExtIEs_Size = 0;

void init_Ass_RAB_Parameters_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  AuthorisedPLMNs_ExtIEs                                    */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION AuthorisedPLMNs_ExtIEs[1];
int AuthorisedPLMNs_ExtIEs_Size = 0;

void init_AuthorisedPLMNs_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  CellLoadInformation_ExtIEs                                */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION CellLoadInformation_ExtIEs[1];
int CellLoadInformation_ExtIEs_Size = 0;

void init_CellLoadInformation_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  CellLoadInformationGroup_ExtIEs                           */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION CellLoadInformationGroup_ExtIEs[1];
int CellLoadInformationGroup_ExtIEs_Size = 0;

void init_CellLoadInformationGroup_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  CriticalityDiagnostics_ExtIEs                             */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION CriticalityDiagnostics_ExtIEs[1];
int CriticalityDiagnostics_ExtIEs_Size = 0;

void init_CriticalityDiagnostics_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  CriticalityDiagnostics_IE_List_ExtIEs                     */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION CriticalityDiagnostics_IE_List_ExtIEs[2];
int CriticalityDiagnostics_IE_List_ExtIEs_Size = 2;

void init_CriticalityDiagnostics_IE_List_ExtIEs(ASN1CTXT *pctxt)
{

   CriticalityDiagnostics_IE_List_ExtIEs[0].id = 88;
   CriticalityDiagnostics_IE_List_ExtIEs[0].criticality = ignore;
   CriticalityDiagnostics_IE_List_ExtIEs[0].ExtensionSize = sizeof(_CriticalityDiagnostics_IE_List_ExtIEs_Extension);
   CriticalityDiagnostics_IE_List_ExtIEs[0].encodeExtension = &asn1PE__CriticalityDiagnostics_IE_List_ExtIEs_Extension;
   CriticalityDiagnostics_IE_List_ExtIEs[0].decodeExtension = &asn1PD__CriticalityDiagnostics_IE_List_ExtIEs_Extension;
   CriticalityDiagnostics_IE_List_ExtIEs[0].printExtension = &asn1Print__CriticalityDiagnostics_IE_List_ExtIEs_Extension;
   CriticalityDiagnostics_IE_List_ExtIEs[0].presence = optional;

   CriticalityDiagnostics_IE_List_ExtIEs[1].id = 93;
   CriticalityDiagnostics_IE_List_ExtIEs[1].criticality = ignore;
   CriticalityDiagnostics_IE_List_ExtIEs[1].ExtensionSize = sizeof(_CriticalityDiagnostics_IE_List_ExtIEs_Extension_1);
   CriticalityDiagnostics_IE_List_ExtIEs[1].encodeExtension = &asn1PE__CriticalityDiagnostics_IE_List_ExtIEs_Extension_1;
   CriticalityDiagnostics_IE_List_ExtIEs[1].decodeExtension = &asn1PD__CriticalityDiagnostics_IE_List_ExtIEs_Extension_1;
   CriticalityDiagnostics_IE_List_ExtIEs[1].printExtension = &asn1Print__CriticalityDiagnostics_IE_List_ExtIEs_Extension_1;
   CriticalityDiagnostics_IE_List_ExtIEs[1].presence = mandatory;

}

/**************************************************************/
/*                                                            */
/*  MessageStructure_ExtIEs                                   */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION MessageStructure_ExtIEs[1];
int MessageStructure_ExtIEs_Size = 0;

void init_MessageStructure_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  CGI_ExtIEs                                                */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION CGI_ExtIEs[1];
int CGI_ExtIEs_Size = 1;

void init_CGI_ExtIEs(ASN1CTXT *pctxt)
{

   CGI_ExtIEs[0].id = 55;
   CGI_ExtIEs[0].criticality = ignore;
   CGI_ExtIEs[0].ExtensionSize = sizeof(_CGI_ExtIEs_Extension);
   CGI_ExtIEs[0].encodeExtension = &asn1PE__CGI_ExtIEs_Extension;
   CGI_ExtIEs[0].decodeExtension = &asn1PD__CGI_ExtIEs_Extension;
   CGI_ExtIEs[0].printExtension = &asn1Print__CGI_ExtIEs_Extension;
   CGI_ExtIEs[0].presence = optional;

}

/**************************************************************/
/*                                                            */
/*  DeltaRAListofIdleModeUEs_ExtIEs                           */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION DeltaRAListofIdleModeUEs_ExtIEs[1];
int DeltaRAListofIdleModeUEs_ExtIEs_Size = 0;

void init_DeltaRAListofIdleModeUEs_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  EncryptionInformation_ExtIEs                              */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION EncryptionInformation_ExtIEs[1];
int EncryptionInformation_ExtIEs_Size = 0;

void init_EncryptionInformation_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  GeographicalCoordinates_ExtIEs                            */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION GeographicalCoordinates_ExtIEs[1];
int GeographicalCoordinates_ExtIEs_Size = 0;

void init_GeographicalCoordinates_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  GA_EllipsoidArc_ExtIEs                                    */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION GA_EllipsoidArc_ExtIEs[1];
int GA_EllipsoidArc_ExtIEs_Size = 0;

void init_GA_EllipsoidArc_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  GA_Point_ExtIEs                                           */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION GA_Point_ExtIEs[1];
int GA_Point_ExtIEs_Size = 0;

void init_GA_Point_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  GA_PointWithAltitude_ExtIEs                               */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION GA_PointWithAltitude_ExtIEs[1];
int GA_PointWithAltitude_ExtIEs_Size = 0;

void init_GA_PointWithAltitude_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  GA_PointWithAltitudeAndUncertaintyEllipsoid_ExtIEs        */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION GA_PointWithAltitudeAndUncertaintyEllipsoid_ExtIEs[1];
int GA_PointWithAltitudeAndUncertaintyEllipsoid_ExtIEs_Size = 0;

void init_GA_PointWithAltitudeAndUncertaintyEllipsoid_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  GA_PointWithUnCertainty_ExtIEs                            */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION GA_PointWithUnCertainty_ExtIEs[1];
int GA_PointWithUnCertainty_ExtIEs_Size = 0;

void init_GA_PointWithUnCertainty_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  GA_PointWithUnCertaintyEllipse_ExtIEs                     */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION GA_PointWithUnCertaintyEllipse_ExtIEs[1];
int GA_PointWithUnCertaintyEllipse_ExtIEs_Size = 0;

void init_GA_PointWithUnCertaintyEllipse_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  GA_Polygon_ExtIEs                                         */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION GA_Polygon_ExtIEs[1];
int GA_Polygon_ExtIEs_Size = 0;

void init_GA_Polygon_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  GERAN_Cell_ID_ExtIEs                                      */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION GERAN_Cell_ID_ExtIEs[1];
int GERAN_Cell_ID_ExtIEs_Size = 0;

void init_GERAN_Cell_ID_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  IMEIGroup_ExtIEs                                          */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION IMEIGroup_ExtIEs[1];
int IMEIGroup_ExtIEs_Size = 0;

void init_IMEIGroup_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  IMEISVGroup_ExtIEs                                        */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION IMEISVGroup_ExtIEs[1];
int IMEISVGroup_ExtIEs_Size = 0;

void init_IMEISVGroup_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  IntegrityProtectionInformation_ExtIEs                     */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION IntegrityProtectionInformation_ExtIEs[1];
int IntegrityProtectionInformation_ExtIEs_Size = 0;

void init_IntegrityProtectionInformation_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  InterSystemInformation_TransparentContainer_ExtIEs        */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION InterSystemInformation_TransparentContainer_ExtIEs[1];
int InterSystemInformation_TransparentContainer_ExtIEs_Size = 0;

void init_InterSystemInformation_TransparentContainer_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  LA_LIST_ExtIEs                                            */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION LA_LIST_ExtIEs[1];
int LA_LIST_ExtIEs_Size = 0;

void init_LA_LIST_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  LAI_ExtIEs                                                */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION LAI_ExtIEs[1];
int LAI_ExtIEs_Size = 0;

void init_LAI_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  LastKnownServiceArea_ExtIEs                               */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION LastKnownServiceArea_ExtIEs[1];
int LastKnownServiceArea_ExtIEs_Size = 0;

void init_LastKnownServiceArea_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  InterfacesToTraceItem_ExtIEs                              */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION InterfacesToTraceItem_ExtIEs[1];
int InterfacesToTraceItem_ExtIEs_Size = 0;

void init_InterfacesToTraceItem_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  PLMNs_in_shared_network_ExtIEs                            */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION PLMNs_in_shared_network_ExtIEs[1];
int PLMNs_in_shared_network_ExtIEs_Size = 0;

void init_PLMNs_in_shared_network_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  PositionData_ExtIEs                                       */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION PositionData_ExtIEs[1];
int PositionData_ExtIEs_Size = 0;

void init_PositionData_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  RAB_Parameters_ExtIEs                                     */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION RAB_Parameters_ExtIEs[1];
int RAB_Parameters_ExtIEs_Size = 1;

void init_RAB_Parameters_ExtIEs(ASN1CTXT *pctxt)
{

   RAB_Parameters_ExtIEs[0].id = 116;
   RAB_Parameters_ExtIEs[0].criticality = ignore;
   RAB_Parameters_ExtIEs[0].ExtensionSize = sizeof(_RAB_Parameters_ExtIEs_Extension);
   RAB_Parameters_ExtIEs[0].encodeExtension = &asn1PE__RAB_Parameters_ExtIEs_Extension;
   RAB_Parameters_ExtIEs[0].decodeExtension = &asn1PD__RAB_Parameters_ExtIEs_Extension;
   RAB_Parameters_ExtIEs[0].printExtension = &asn1Print__RAB_Parameters_ExtIEs_Extension;
   RAB_Parameters_ExtIEs[0].presence = optional;

}

/**************************************************************/
/*                                                            */
/*  RAB_TrCH_MappingItem_ExtIEs                               */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION RAB_TrCH_MappingItem_ExtIEs[1];
int RAB_TrCH_MappingItem_ExtIEs_Size = 1;

void init_RAB_TrCH_MappingItem_ExtIEs(ASN1CTXT *pctxt)
{

   RAB_TrCH_MappingItem_ExtIEs[0].id = 3;
   RAB_TrCH_MappingItem_ExtIEs[0].criticality = ignore;
   RAB_TrCH_MappingItem_ExtIEs[0].ExtensionSize = sizeof(_RAB_TrCH_MappingItem_ExtIEs_Extension);
   RAB_TrCH_MappingItem_ExtIEs[0].encodeExtension = &asn1PE__RAB_TrCH_MappingItem_ExtIEs_Extension;
   RAB_TrCH_MappingItem_ExtIEs[0].decodeExtension = &asn1PD__RAB_TrCH_MappingItem_ExtIEs_Extension;
   RAB_TrCH_MappingItem_ExtIEs[0].printExtension = &asn1Print__RAB_TrCH_MappingItem_ExtIEs_Extension;
   RAB_TrCH_MappingItem_ExtIEs[0].presence = optional;

}

/**************************************************************/
/*                                                            */
/*  RAI_ExtIEs                                                */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION RAI_ExtIEs[1];
int RAI_ExtIEs_Size = 0;

void init_RAI_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  NotEmptyRAListofIdleModeUEs_ExtIEs                        */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION NotEmptyRAListofIdleModeUEs_ExtIEs[1];
int NotEmptyRAListofIdleModeUEs_ExtIEs_Size = 0;

void init_NotEmptyRAListofIdleModeUEs_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  MBMSIPMulticastAddressandAPNlist_ExtIEs                   */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION MBMSIPMulticastAddressandAPNlist_ExtIEs[1];
int MBMSIPMulticastAddressandAPNlist_ExtIEs_Size = 0;

void init_MBMSIPMulticastAddressandAPNlist_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  Requested_RAB_Parameter_Values_ExtIEs                     */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION Requested_RAB_Parameter_Values_ExtIEs[1];
int Requested_RAB_Parameter_Values_ExtIEs_Size = 1;

void init_Requested_RAB_Parameter_Values_ExtIEs(ASN1CTXT *pctxt)
{

   Requested_RAB_Parameter_Values_ExtIEs[0].id = 159;
   Requested_RAB_Parameter_Values_ExtIEs[0].criticality = ignore;
   Requested_RAB_Parameter_Values_ExtIEs[0].ExtensionSize = sizeof(_Requested_RAB_Parameter_Values_ExtIEs_Extension);
   Requested_RAB_Parameter_Values_ExtIEs[0].encodeExtension = &asn1PE__Requested_RAB_Parameter_Values_ExtIEs_Extension;
   Requested_RAB_Parameter_Values_ExtIEs[0].decodeExtension = &asn1PD__Requested_RAB_Parameter_Values_ExtIEs_Extension;
   Requested_RAB_Parameter_Values_ExtIEs[0].printExtension = &asn1Print__Requested_RAB_Parameter_Values_ExtIEs_Extension;
   Requested_RAB_Parameter_Values_ExtIEs[0].presence = optional;

}

/**************************************************************/
/*                                                            */
/*  ResidualBitErrorRatio_ExtIEs                              */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION ResidualBitErrorRatio_ExtIEs[1];
int ResidualBitErrorRatio_ExtIEs_Size = 0;

void init_ResidualBitErrorRatio_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  RIM_Transfer_ExtIEs                                       */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION RIM_Transfer_ExtIEs[1];
int RIM_Transfer_ExtIEs_Size = 0;

void init_RIM_Transfer_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  RNCTraceInformation_ExtIEs                                */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION RNCTraceInformation_ExtIEs[1];
int RNCTraceInformation_ExtIEs_Size = 0;

void init_RNCTraceInformation_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  SAI_ExtIEs                                                */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION SAI_ExtIEs[1];
int SAI_ExtIEs_Size = 0;

void init_SAI_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  Shared_Network_Information_ExtIEs                         */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION Shared_Network_Information_ExtIEs[1];
int Shared_Network_Information_ExtIEs_Size = 0;

void init_Shared_Network_Information_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  SDU_ErrorRatio_ExtIEs                                     */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION SDU_ErrorRatio_ExtIEs[1];
int SDU_ErrorRatio_ExtIEs_Size = 0;

void init_SDU_ErrorRatio_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  SDU_FormatInformationParameters_ExtIEs                    */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION SDU_FormatInformationParameters_ExtIEs[1];
int SDU_FormatInformationParameters_ExtIEs_Size = 0;

void init_SDU_FormatInformationParameters_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  SDU_Parameters_ExtIEs                                     */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION SDU_Parameters_ExtIEs[1];
int SDU_Parameters_ExtIEs_Size = 0;

void init_SDU_Parameters_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  SNA_Access_Information_ExtIEs                             */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION SNA_Access_Information_ExtIEs[1];
int SNA_Access_Information_ExtIEs_Size = 0;

void init_SNA_Access_Information_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  SourceRNC_ID_ExtIEs                                       */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION SourceRNC_ID_ExtIEs[1];
int SourceRNC_ID_ExtIEs_Size = 0;

void init_SourceRNC_ID_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs         */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[4];
int SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Size = 4;

void init_SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs(ASN1CTXT *pctxt)
{

   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[0].id = 98;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[0].criticality = reject;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[0].ExtensionSize = sizeof(_SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension);
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[0].encodeExtension = &asn1PE__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[0].decodeExtension = &asn1PD__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[0].printExtension = &asn1Print__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[0].presence = optional;

   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[1].id = 121;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[1].criticality = ignore;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[1].ExtensionSize = sizeof(_SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_1);
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[1].encodeExtension = &asn1PE__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_1;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[1].decodeExtension = &asn1PD__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_1;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[1].printExtension = &asn1Print__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_1;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[1].presence = optional;

   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[2].id = 124;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[2].criticality = ignore;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[2].ExtensionSize = sizeof(_SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_2);
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[2].encodeExtension = &asn1PE__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_2;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[2].decodeExtension = &asn1PD__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_2;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[2].printExtension = &asn1Print__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_2;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[2].presence = optional;

   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[3].id = 156;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[3].criticality = ignore;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[3].ExtensionSize = sizeof(_SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_3);
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[3].encodeExtension = &asn1PE__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_3;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[3].decodeExtension = &asn1PD__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_3;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[3].printExtension = &asn1Print__SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Extension_3;
   SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[3].presence = optional;

}

/**************************************************************/
/*                                                            */
/*  SourceUTRANCellID_ExtIEs                                  */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION SourceUTRANCellID_ExtIEs[1];
int SourceUTRANCellID_ExtIEs_Size = 0;

void init_SourceUTRANCellID_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  SRB_TrCH_MappingItem_ExtIEs                               */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION SRB_TrCH_MappingItem_ExtIEs[1];
int SRB_TrCH_MappingItem_ExtIEs_Size = 0;

void init_SRB_TrCH_MappingItem_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  TargetRNC_ID_ExtIEs                                       */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION TargetRNC_ID_ExtIEs[1];
int TargetRNC_ID_ExtIEs_Size = 0;

void init_TargetRNC_ID_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  TargetRNC_ToSourceRNC_TransparentContainer_ExtIEs         */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION TargetRNC_ToSourceRNC_TransparentContainer_ExtIEs[1];
int TargetRNC_ToSourceRNC_TransparentContainer_ExtIEs_Size = 0;

void init_TargetRNC_ToSourceRNC_TransparentContainer_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  TMGI_ExtIEs                                               */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION TMGI_ExtIEs[1];
int TMGI_ExtIEs_Size = 0;

void init_TMGI_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  TracePropagationParameters_ExtIEs                         */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION TracePropagationParameters_ExtIEs[1];
int TracePropagationParameters_ExtIEs_Size = 0;

void init_TracePropagationParameters_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  TraceRecordingSessionInformation_ExtIEs                   */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION TraceRecordingSessionInformation_ExtIEs[1];
int TraceRecordingSessionInformation_ExtIEs_Size = 0;

void init_TraceRecordingSessionInformation_ExtIEs(ASN1CTXT *pctxt)
{

}

/**************************************************************/
/*                                                            */
/*  TrCH_ID_ExtIEs                                            */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION TrCH_ID_ExtIEs[2];
int TrCH_ID_ExtIEs_Size = 2;

void init_TrCH_ID_ExtIEs(ASN1CTXT *pctxt)
{

   TrCH_ID_ExtIEs[0].id = 117;
   TrCH_ID_ExtIEs[0].criticality = ignore;
   TrCH_ID_ExtIEs[0].ExtensionSize = sizeof(_TrCH_ID_ExtIEs_Extension);
   TrCH_ID_ExtIEs[0].encodeExtension = &asn1PE__TrCH_ID_ExtIEs_Extension;
   TrCH_ID_ExtIEs[0].decodeExtension = &asn1PD__TrCH_ID_ExtIEs_Extension;
   TrCH_ID_ExtIEs[0].printExtension = &asn1Print__TrCH_ID_ExtIEs_Extension;
   TrCH_ID_ExtIEs[0].presence = optional;

   TrCH_ID_ExtIEs[1].id = 160;
   TrCH_ID_ExtIEs[1].criticality = ignore;
   TrCH_ID_ExtIEs[1].ExtensionSize = sizeof(_TrCH_ID_ExtIEs_Extension_1);
   TrCH_ID_ExtIEs[1].encodeExtension = &asn1PE__TrCH_ID_ExtIEs_Extension_1;
   TrCH_ID_ExtIEs[1].decodeExtension = &asn1PD__TrCH_ID_ExtIEs_Extension_1;
   TrCH_ID_ExtIEs[1].printExtension = &asn1Print__TrCH_ID_ExtIEs_Extension_1;
   TrCH_ID_ExtIEs[1].presence = optional;

}

/**************************************************************/
/*                                                            */
/*  UESBI_Iu_ExtIEs                                           */
/*                                                            */
/**************************************************************/

RANAP_PROTOCOL_EXTENSION UESBI_Iu_ExtIEs[1];
int UESBI_Iu_ExtIEs_Size = 0;

void init_UESBI_Iu_ExtIEs(ASN1CTXT *pctxt)
{

}

