/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#ifndef RANAP_CONTAINERSCLASS_H
#define RANAP_CONTAINERSCLASS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1per.h"
#include "rtTable.h"
#include "RANAP-Containers.h"
#include "RANAP-Constants.h"

/* Class definitions */

/**************************************************************/
/*                                                            */
/*  RANAP_PROTOCOL_IES                                        */
/*                                                            */
/**************************************************************/

typedef struct RANAP_PROTOCOL_IES {
   OSUINT16 id;
   OSUINT32 criticality;
   int ValueSize;
   int (*encodeValue) (ASN1CTXT* , void * );
   int (*decodeValue) (ASN1CTXT* , void * );
   void (*printValue) (ASN1ConstCharPtr , void * );
   OSUINT32 presence;
} RANAP_PROTOCOL_IES;

/**************************************************************/
/*                                                            */
/*  RANAP_PROTOCOL_IES_PAIR                                   */
/*                                                            */
/**************************************************************/

typedef struct RANAP_PROTOCOL_IES_PAIR {
   OSUINT16 id;
   OSUINT32 firstCriticality;
   int FirstValueSize;
   int (*encodeFirstValue) (ASN1CTXT* , void * );
   int (*decodeFirstValue) (ASN1CTXT* , void * );
   void (*printFirstValue) (ASN1ConstCharPtr , void * );
   OSUINT32 secondCriticality;
   int SecondValueSize;
   int (*encodeSecondValue) (ASN1CTXT* , void * );
   int (*decodeSecondValue) (ASN1CTXT* , void * );
   void (*printSecondValue) (ASN1ConstCharPtr , void * );
   OSUINT32 presence;
} RANAP_PROTOCOL_IES_PAIR;

/**************************************************************/
/*                                                            */
/*  RANAP_PROTOCOL_EXTENSION                                  */
/*                                                            */
/**************************************************************/

typedef struct RANAP_PROTOCOL_EXTENSION {
   OSUINT16 id;
   OSUINT32 criticality;
   int ExtensionSize;
   int (*encodeExtension) (ASN1CTXT* , void * );
   int (*decodeExtension) (ASN1CTXT* , void * );
   void (*printExtension) (ASN1ConstCharPtr , void * );
   OSUINT32 presence;
} RANAP_PROTOCOL_EXTENSION;

/**************************************************************/
/*                                                            */
/*  RANAP_PRIVATE_IES                                         */
/*                                                            */
/**************************************************************/

typedef struct RANAP_PRIVATE_IES {
   PrivateIE_ID id;
   OSUINT32 criticality;
   int ValueSize;
   int (*encodeValue) (ASN1CTXT* , void * );
   int (*decodeValue) (ASN1CTXT* , void * );
   void (*printValue) (ASN1ConstCharPtr , void * );
   OSUINT32 presence;
} RANAP_PRIVATE_IES;

#ifdef __cplusplus
}
#endif

#endif
