/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#ifndef RANAP_IESTABLE_H
#define RANAP_IESTABLE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1per.h"
#include "rtTable.h"
#include "RANAP-IEs.h"
#include "RANAP-Constants.h"
#include "RANAP-ContainersClass.h"

/* Intialization function */
extern void RANAP_IEs_init(ASN1CTXT *pctxt);

/* Object definitions */

/* ObjectSet definitions */

extern struct RANAP_PROTOCOL_EXTENSION AllocationOrRetentionPriority_ExtIEs[];
extern int AllocationOrRetentionPriority_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION Alt_RAB_Parameters_ExtIEs[];
extern int Alt_RAB_Parameters_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION Ass_RAB_Parameters_ExtIEs[];
extern int Ass_RAB_Parameters_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION AuthorisedPLMNs_ExtIEs[];
extern int AuthorisedPLMNs_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION CellLoadInformation_ExtIEs[];
extern int CellLoadInformation_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION CellLoadInformationGroup_ExtIEs[];
extern int CellLoadInformationGroup_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION CriticalityDiagnostics_ExtIEs[];
extern int CriticalityDiagnostics_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION CriticalityDiagnostics_IE_List_ExtIEs[];
extern int CriticalityDiagnostics_IE_List_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION MessageStructure_ExtIEs[];
extern int MessageStructure_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION CGI_ExtIEs[];
extern int CGI_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION DeltaRAListofIdleModeUEs_ExtIEs[];
extern int DeltaRAListofIdleModeUEs_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION EncryptionInformation_ExtIEs[];
extern int EncryptionInformation_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION GeographicalCoordinates_ExtIEs[];
extern int GeographicalCoordinates_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION GA_EllipsoidArc_ExtIEs[];
extern int GA_EllipsoidArc_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION GA_Point_ExtIEs[];
extern int GA_Point_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION GA_PointWithAltitude_ExtIEs[];
extern int GA_PointWithAltitude_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION GA_PointWithAltitudeAndUncertaintyEllipsoid_ExtIEs[];
extern int GA_PointWithAltitudeAndUncertaintyEllipsoid_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION GA_PointWithUnCertainty_ExtIEs[];
extern int GA_PointWithUnCertainty_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION GA_PointWithUnCertaintyEllipse_ExtIEs[];
extern int GA_PointWithUnCertaintyEllipse_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION GA_Polygon_ExtIEs[];
extern int GA_Polygon_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION GERAN_Cell_ID_ExtIEs[];
extern int GERAN_Cell_ID_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION IMEIGroup_ExtIEs[];
extern int IMEIGroup_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION IMEISVGroup_ExtIEs[];
extern int IMEISVGroup_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION IntegrityProtectionInformation_ExtIEs[];
extern int IntegrityProtectionInformation_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION InterSystemInformation_TransparentContainer_ExtIEs[];
extern int InterSystemInformation_TransparentContainer_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION LA_LIST_ExtIEs[];
extern int LA_LIST_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION LAI_ExtIEs[];
extern int LAI_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION LastKnownServiceArea_ExtIEs[];
extern int LastKnownServiceArea_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION InterfacesToTraceItem_ExtIEs[];
extern int InterfacesToTraceItem_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION PLMNs_in_shared_network_ExtIEs[];
extern int PLMNs_in_shared_network_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION PositionData_ExtIEs[];
extern int PositionData_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION RAB_Parameters_ExtIEs[];
extern int RAB_Parameters_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION RAB_TrCH_MappingItem_ExtIEs[];
extern int RAB_TrCH_MappingItem_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION RAI_ExtIEs[];
extern int RAI_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION NotEmptyRAListofIdleModeUEs_ExtIEs[];
extern int NotEmptyRAListofIdleModeUEs_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION MBMSIPMulticastAddressandAPNlist_ExtIEs[];
extern int MBMSIPMulticastAddressandAPNlist_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION Requested_RAB_Parameter_Values_ExtIEs[];
extern int Requested_RAB_Parameter_Values_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION ResidualBitErrorRatio_ExtIEs[];
extern int ResidualBitErrorRatio_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION RIM_Transfer_ExtIEs[];
extern int RIM_Transfer_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION RNCTraceInformation_ExtIEs[];
extern int RNCTraceInformation_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION SAI_ExtIEs[];
extern int SAI_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION Shared_Network_Information_ExtIEs[];
extern int Shared_Network_Information_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION SDU_ErrorRatio_ExtIEs[];
extern int SDU_ErrorRatio_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION SDU_FormatInformationParameters_ExtIEs[];
extern int SDU_FormatInformationParameters_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION SDU_Parameters_ExtIEs[];
extern int SDU_Parameters_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION SNA_Access_Information_ExtIEs[];
extern int SNA_Access_Information_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION SourceRNC_ID_ExtIEs[];
extern int SourceRNC_ID_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs[];
extern int SourceRNC_ToTargetRNC_TransparentContainer_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION SourceUTRANCellID_ExtIEs[];
extern int SourceUTRANCellID_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION SRB_TrCH_MappingItem_ExtIEs[];
extern int SRB_TrCH_MappingItem_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION TargetRNC_ID_ExtIEs[];
extern int TargetRNC_ID_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION TargetRNC_ToSourceRNC_TransparentContainer_ExtIEs[];
extern int TargetRNC_ToSourceRNC_TransparentContainer_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION TMGI_ExtIEs[];
extern int TMGI_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION TracePropagationParameters_ExtIEs[];
extern int TracePropagationParameters_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION TraceRecordingSessionInformation_ExtIEs[];
extern int TraceRecordingSessionInformation_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION TrCH_ID_ExtIEs[];
extern int TrCH_ID_ExtIEs_Size;
extern struct RANAP_PROTOCOL_EXTENSION UESBI_Iu_ExtIEs[];
extern int UESBI_Iu_ExtIEs_Size;

#ifdef __cplusplus
}
#endif

#endif
