/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#include "asn1intl.h"
#include "RANAP-PDU-DescriptionsTable.h"
#include "RANAP-PDU-ContentsTable.h"
#include "RANAP-IEsTable.h"

/**************************************************************/
/*                                                            */
/*  _iu_Release_InitiatingMessage                             */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__iu_Release_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _iu_Release_InitiatingMessage *pvalue = (_iu_Release_InitiatingMessage*) pvalue_;

   stat = asn1PD_Iu_ReleaseCommand (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _iu_Release_SuccessfulOutcome                             */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__iu_Release_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _iu_Release_SuccessfulOutcome *pvalue = (_iu_Release_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_Iu_ReleaseComplete (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationPreparation_InitiatingMessage                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationPreparation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationPreparation_InitiatingMessage *pvalue = (_relocationPreparation_InitiatingMessage*) pvalue_;

   stat = asn1PD_RelocationRequired (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationPreparation_SuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationPreparation_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationPreparation_SuccessfulOutcome *pvalue = (_relocationPreparation_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_RelocationCommand (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationPreparation_UnsuccessfulOutcome                */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationPreparation_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationPreparation_UnsuccessfulOutcome *pvalue = (_relocationPreparation_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_RelocationPreparationFailure (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationResourceAllocation_InitiatingMessage           */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationResourceAllocation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationResourceAllocation_InitiatingMessage *pvalue = (_relocationResourceAllocation_InitiatingMessage*) pvalue_;

   stat = asn1PD_RelocationRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationResourceAllocation_SuccessfulOutcome           */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationResourceAllocation_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationResourceAllocation_SuccessfulOutcome *pvalue = (_relocationResourceAllocation_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_RelocationRequestAcknowledge (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationResourceAllocation_UnsuccessfulOutcome         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationResourceAllocation_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationResourceAllocation_UnsuccessfulOutcome *pvalue = (_relocationResourceAllocation_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_RelocationFailure (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationCancel_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationCancel_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationCancel_InitiatingMessage *pvalue = (_relocationCancel_InitiatingMessage*) pvalue_;

   stat = asn1PD_RelocationCancel (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationCancel_SuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationCancel_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationCancel_SuccessfulOutcome *pvalue = (_relocationCancel_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_RelocationCancelAcknowledge (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _sRNS_ContextTransfer_InitiatingMessage                   */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__sRNS_ContextTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _sRNS_ContextTransfer_InitiatingMessage *pvalue = (_sRNS_ContextTransfer_InitiatingMessage*) pvalue_;

   stat = asn1PD_SRNS_ContextRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _sRNS_ContextTransfer_SuccessfulOutcome                   */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__sRNS_ContextTransfer_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _sRNS_ContextTransfer_SuccessfulOutcome *pvalue = (_sRNS_ContextTransfer_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_SRNS_ContextResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _securityModeControl_InitiatingMessage                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__securityModeControl_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _securityModeControl_InitiatingMessage *pvalue = (_securityModeControl_InitiatingMessage*) pvalue_;

   stat = asn1PD_SecurityModeCommand (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _securityModeControl_SuccessfulOutcome                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__securityModeControl_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _securityModeControl_SuccessfulOutcome *pvalue = (_securityModeControl_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_SecurityModeComplete (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _securityModeControl_UnsuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__securityModeControl_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _securityModeControl_UnsuccessfulOutcome *pvalue = (_securityModeControl_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_SecurityModeReject (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _dataVolumeReport_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__dataVolumeReport_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _dataVolumeReport_InitiatingMessage *pvalue = (_dataVolumeReport_InitiatingMessage*) pvalue_;

   stat = asn1PD_DataVolumeReportRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _dataVolumeReport_SuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__dataVolumeReport_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _dataVolumeReport_SuccessfulOutcome *pvalue = (_dataVolumeReport_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_DataVolumeReport (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _reset_InitiatingMessage                                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__reset_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _reset_InitiatingMessage *pvalue = (_reset_InitiatingMessage*) pvalue_;

   stat = asn1PD_Reset (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _reset_SuccessfulOutcome                                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__reset_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _reset_SuccessfulOutcome *pvalue = (_reset_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_ResetAcknowledge (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _rAB_ReleaseRequest_InitiatingMessage                     */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__rAB_ReleaseRequest_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _rAB_ReleaseRequest_InitiatingMessage *pvalue = (_rAB_ReleaseRequest_InitiatingMessage*) pvalue_;

   stat = asn1PD_RAB_ReleaseRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _iu_ReleaseRequest_InitiatingMessage                      */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__iu_ReleaseRequest_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _iu_ReleaseRequest_InitiatingMessage *pvalue = (_iu_ReleaseRequest_InitiatingMessage*) pvalue_;

   stat = asn1PD_Iu_ReleaseRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationDetect_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationDetect_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationDetect_InitiatingMessage *pvalue = (_relocationDetect_InitiatingMessage*) pvalue_;

   stat = asn1PD_RelocationDetect (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _relocationComplete_InitiatingMessage                     */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__relocationComplete_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _relocationComplete_InitiatingMessage *pvalue = (_relocationComplete_InitiatingMessage*) pvalue_;

   stat = asn1PD_RelocationComplete (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _paging_InitiatingMessage                                 */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__paging_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _paging_InitiatingMessage *pvalue = (_paging_InitiatingMessage*) pvalue_;

   stat = asn1PD_Paging (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _commonID_InitiatingMessage                               */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__commonID_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _commonID_InitiatingMessage *pvalue = (_commonID_InitiatingMessage*) pvalue_;

   stat = asn1PD_CommonID (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _cN_InvokeTrace_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__cN_InvokeTrace_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _cN_InvokeTrace_InitiatingMessage *pvalue = (_cN_InvokeTrace_InitiatingMessage*) pvalue_;

   stat = asn1PD_CN_InvokeTrace (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _cN_DeactivateTrace_InitiatingMessage                     */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__cN_DeactivateTrace_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _cN_DeactivateTrace_InitiatingMessage *pvalue = (_cN_DeactivateTrace_InitiatingMessage*) pvalue_;

   stat = asn1PD_CN_DeactivateTrace (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _locationReportingControl_InitiatingMessage               */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__locationReportingControl_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _locationReportingControl_InitiatingMessage *pvalue = (_locationReportingControl_InitiatingMessage*) pvalue_;

   stat = asn1PD_LocationReportingControl (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _locationReport_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__locationReport_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _locationReport_InitiatingMessage *pvalue = (_locationReport_InitiatingMessage*) pvalue_;

   stat = asn1PD_LocationReport (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _initialUE_Message_InitiatingMessage                      */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__initialUE_Message_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _initialUE_Message_InitiatingMessage *pvalue = (_initialUE_Message_InitiatingMessage*) pvalue_;

   stat = asn1PD_InitialUE_Message (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _directTransfer_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__directTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _directTransfer_InitiatingMessage *pvalue = (_directTransfer_InitiatingMessage*) pvalue_;

   stat = asn1PD_DirectTransfer (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _overloadControl_InitiatingMessage                        */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__overloadControl_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _overloadControl_InitiatingMessage *pvalue = (_overloadControl_InitiatingMessage*) pvalue_;

   stat = asn1PD_Overload (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _errorIndication_InitiatingMessage                        */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__errorIndication_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _errorIndication_InitiatingMessage *pvalue = (_errorIndication_InitiatingMessage*) pvalue_;

   stat = asn1PD_ErrorIndication (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _sRNS_DataForward_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__sRNS_DataForward_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _sRNS_DataForward_InitiatingMessage *pvalue = (_sRNS_DataForward_InitiatingMessage*) pvalue_;

   stat = asn1PD_SRNS_DataForwardCommand (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _forwardSRNS_Context_InitiatingMessage                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__forwardSRNS_Context_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _forwardSRNS_Context_InitiatingMessage *pvalue = (_forwardSRNS_Context_InitiatingMessage*) pvalue_;

   stat = asn1PD_ForwardSRNS_Context (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _rAB_Assignment_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__rAB_Assignment_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _rAB_Assignment_InitiatingMessage *pvalue = (_rAB_Assignment_InitiatingMessage*) pvalue_;

   stat = asn1PD_RAB_AssignmentRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _rAB_Assignment_Outcome                                   */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__rAB_Assignment_Outcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _rAB_Assignment_Outcome *pvalue = (_rAB_Assignment_Outcome*) pvalue_;

   stat = asn1PD_RAB_AssignmentResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _privateMessage_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__privateMessage_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _privateMessage_InitiatingMessage *pvalue = (_privateMessage_InitiatingMessage*) pvalue_;

   stat = asn1PD_PrivateMessage (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _resetResource_InitiatingMessage                          */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__resetResource_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _resetResource_InitiatingMessage *pvalue = (_resetResource_InitiatingMessage*) pvalue_;

   stat = asn1PD_ResetResource (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _resetResource_SuccessfulOutcome                          */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__resetResource_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _resetResource_SuccessfulOutcome *pvalue = (_resetResource_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_ResetResourceAcknowledge (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _rANAP_Relocation_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__rANAP_Relocation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _rANAP_Relocation_InitiatingMessage *pvalue = (_rANAP_Relocation_InitiatingMessage*) pvalue_;

   stat = asn1PD_RANAP_RelocationInformation (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _rAB_ModifyRequest_InitiatingMessage                      */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__rAB_ModifyRequest_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _rAB_ModifyRequest_InitiatingMessage *pvalue = (_rAB_ModifyRequest_InitiatingMessage*) pvalue_;

   stat = asn1PD_RAB_ModifyRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _locationRelatedData_InitiatingMessage                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__locationRelatedData_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _locationRelatedData_InitiatingMessage *pvalue = (_locationRelatedData_InitiatingMessage*) pvalue_;

   stat = asn1PD_LocationRelatedDataRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _locationRelatedData_SuccessfulOutcome                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__locationRelatedData_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _locationRelatedData_SuccessfulOutcome *pvalue = (_locationRelatedData_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_LocationRelatedDataResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _locationRelatedData_UnsuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__locationRelatedData_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _locationRelatedData_UnsuccessfulOutcome *pvalue = (_locationRelatedData_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_LocationRelatedDataFailure (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _informationTransfer_InitiatingMessage                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__informationTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _informationTransfer_InitiatingMessage *pvalue = (_informationTransfer_InitiatingMessage*) pvalue_;

   stat = asn1PD_InformationTransferIndication (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _informationTransfer_SuccessfulOutcome                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__informationTransfer_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _informationTransfer_SuccessfulOutcome *pvalue = (_informationTransfer_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_InformationTransferConfirmation (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _informationTransfer_UnsuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__informationTransfer_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _informationTransfer_UnsuccessfulOutcome *pvalue = (_informationTransfer_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_InformationTransferFailure (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _uESpecificInformation_InitiatingMessage                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__uESpecificInformation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _uESpecificInformation_InitiatingMessage *pvalue = (_uESpecificInformation_InitiatingMessage*) pvalue_;

   stat = asn1PD_UESpecificInformationIndication (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _directInformationTransfer_InitiatingMessage              */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__directInformationTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _directInformationTransfer_InitiatingMessage *pvalue = (_directInformationTransfer_InitiatingMessage*) pvalue_;

   stat = asn1PD_DirectInformationTransfer (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _uplinkInformationExchange_InitiatingMessage              */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__uplinkInformationExchange_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _uplinkInformationExchange_InitiatingMessage *pvalue = (_uplinkInformationExchange_InitiatingMessage*) pvalue_;

   stat = asn1PD_UplinkInformationExchangeRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _uplinkInformationExchange_SuccessfulOutcome              */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__uplinkInformationExchange_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _uplinkInformationExchange_SuccessfulOutcome *pvalue = (_uplinkInformationExchange_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_UplinkInformationExchangeResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _uplinkInformationExchange_UnsuccessfulOutcome            */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__uplinkInformationExchange_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _uplinkInformationExchange_UnsuccessfulOutcome *pvalue = (_uplinkInformationExchange_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_UplinkInformationExchangeFailure (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStart_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSSessionStart_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSSessionStart_InitiatingMessage *pvalue = (_mBMSSessionStart_InitiatingMessage*) pvalue_;

   stat = asn1PD_MBMSSessionStart (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStart_SuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSSessionStart_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSSessionStart_SuccessfulOutcome *pvalue = (_mBMSSessionStart_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSSessionStartResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStart_UnsuccessfulOutcome                     */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSSessionStart_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSSessionStart_UnsuccessfulOutcome *pvalue = (_mBMSSessionStart_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSSessionStartFailure (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSSessionUpdate_InitiatingMessage                      */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSSessionUpdate_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSSessionUpdate_InitiatingMessage *pvalue = (_mBMSSessionUpdate_InitiatingMessage*) pvalue_;

   stat = asn1PD_MBMSSessionUpdate (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSSessionUpdate_SuccessfulOutcome                      */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSSessionUpdate_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSSessionUpdate_SuccessfulOutcome *pvalue = (_mBMSSessionUpdate_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSSessionUpdateResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSSessionUpdate_UnsuccessfulOutcome                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSSessionUpdate_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSSessionUpdate_UnsuccessfulOutcome *pvalue = (_mBMSSessionUpdate_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSSessionUpdateFailure (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStop_InitiatingMessage                        */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSSessionStop_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSSessionStop_InitiatingMessage *pvalue = (_mBMSSessionStop_InitiatingMessage*) pvalue_;

   stat = asn1PD_MBMSSessionStop (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStop_SuccessfulOutcome                        */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSSessionStop_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSSessionStop_SuccessfulOutcome *pvalue = (_mBMSSessionStop_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSSessionStopResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSUELinking_InitiatingMessage                          */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSUELinking_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSUELinking_InitiatingMessage *pvalue = (_mBMSUELinking_InitiatingMessage*) pvalue_;

   stat = asn1PD_MBMSUELinkingRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSUELinking_Outcome                                    */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSUELinking_Outcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSUELinking_Outcome *pvalue = (_mBMSUELinking_Outcome*) pvalue_;

   stat = asn1PD_MBMSUELinkingResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSRegistration_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSRegistration_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSRegistration_InitiatingMessage *pvalue = (_mBMSRegistration_InitiatingMessage*) pvalue_;

   stat = asn1PD_MBMSRegistrationRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSRegistration_SuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSRegistration_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSRegistration_SuccessfulOutcome *pvalue = (_mBMSRegistration_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSRegistrationResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSRegistration_UnsuccessfulOutcome                     */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSRegistration_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSRegistration_UnsuccessfulOutcome *pvalue = (_mBMSRegistration_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSRegistrationFailure (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSCNDe_Registration_InitiatingMessage                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSCNDe_Registration_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSCNDe_Registration_InitiatingMessage *pvalue = (_mBMSCNDe_Registration_InitiatingMessage*) pvalue_;

   stat = asn1PD_MBMSCNDe_RegistrationRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSCNDe_Registration_SuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSCNDe_Registration_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSCNDe_Registration_SuccessfulOutcome *pvalue = (_mBMSCNDe_Registration_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSCNDe_RegistrationResponse (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSRABEstablishmentIndication_InitiatingMessage         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSRABEstablishmentIndication_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSRABEstablishmentIndication_InitiatingMessage *pvalue = (_mBMSRABEstablishmentIndication_InitiatingMessage*) pvalue_;

   stat = asn1PD_MBMSRABEstablishmentIndication (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSRABRelease_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSRABRelease_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSRABRelease_InitiatingMessage *pvalue = (_mBMSRABRelease_InitiatingMessage*) pvalue_;

   stat = asn1PD_MBMSRABReleaseRequest (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSRABRelease_SuccessfulOutcome                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSRABRelease_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSRABRelease_SuccessfulOutcome *pvalue = (_mBMSRABRelease_SuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSRABRelease (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  _mBMSRABRelease_UnsuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD__mBMSRABRelease_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_)
{
   int stat = 0;

   _mBMSRABRelease_UnsuccessfulOutcome *pvalue = (_mBMSRABRelease_UnsuccessfulOutcome*) pvalue_;

   stat = asn1PD_MBMSRABReleaseFailure (pctxt, pvalue);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  InitiatingMessage                                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_InitiatingMessage (ASN1CTXT* pctxt, InitiatingMessage* pvalue)
{
   int stat = 0;
   ASN1CTXT lctxt;

   /* decode procedureCode */

   stat = asn1PD_ProcedureCode (pctxt, &pvalue->procedureCode);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   /* decode criticality */

   stat = asn1PD_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   /* decode value */

   stat = pd_OpenType (pctxt, &pvalue->value.encoded.data, &pvalue->value.encoded.numocts);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

    /* invoke table constraint function */

   rtCopyContext (&lctxt, pctxt);
   stat = asn1PDTC_InitiatingMessage (pctxt, pvalue);

   rtCopyContext (pctxt, &lctxt);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  InitiatingMessage                                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PDTC_InitiatingMessage (ASN1CTXT* pctxt,
   InitiatingMessage *pvalue)
{
   int stat = 0;
   int index = -1;

   /* check procedureCode */
   for(index = 0; index < RANAP_ELEMENTARY_PROCEDURES_Size; index++) {
      if(rtCmpTCUINT8(&pvalue->procedureCode, &RANAP_ELEMENTARY_PROCEDURES[index].procedureCode) == 0) {
         break;
      }
   }
   if(index == RANAP_ELEMENTARY_PROCEDURES_Size) return 0;

   /* check value */
   stat = pd_setp (pctxt,
         (OSOCTET*)pvalue->value.encoded.data,
         pvalue->value.encoded.numocts,
         pctxt->buffer.aligned);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
   pvalue->value.decoded = rtMemAlloc (pctxt, RANAP_ELEMENTARY_PROCEDURES[index].InitiatingMessageSize);
   stat = RANAP_ELEMENTARY_PROCEDURES[index].decodeInitiatingMessage(pctxt, pvalue->value.decoded );
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   /* use -strict option to validate the "criticality" element */

   return stat;
}

/**************************************************************/
/*                                                            */
/*  SuccessfulOutcome                                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_SuccessfulOutcome (ASN1CTXT* pctxt, SuccessfulOutcome* pvalue)
{
   int stat = 0;
   ASN1CTXT lctxt;

   /* decode procedureCode */

   stat = asn1PD_ProcedureCode (pctxt, &pvalue->procedureCode);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   /* decode criticality */

   stat = asn1PD_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   /* decode value */

   stat = pd_OpenType (pctxt, &pvalue->value.encoded.data, &pvalue->value.encoded.numocts);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

    /* invoke table constraint function */

   rtCopyContext (&lctxt, pctxt);
   stat = asn1PDTC_SuccessfulOutcome (pctxt, pvalue);

   rtCopyContext (pctxt, &lctxt);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  SuccessfulOutcome                                         */
/*                                                            */
/**************************************************************/

EXTERN int asn1PDTC_SuccessfulOutcome (ASN1CTXT* pctxt,
   SuccessfulOutcome *pvalue)
{
   int stat = 0;
   int index = -1;

   /* check procedureCode */
   for(index = 0; index < RANAP_ELEMENTARY_PROCEDURES_Size; index++) {
      if(rtCmpTCUINT8(&pvalue->procedureCode, &RANAP_ELEMENTARY_PROCEDURES[index].procedureCode) == 0) {
         break;
      }
   }
   if(index == RANAP_ELEMENTARY_PROCEDURES_Size) return 0;

   /* check value */
   if(RANAP_ELEMENTARY_PROCEDURES[index].m.SuccessfulOutcomePresent)
   {
      stat = pd_setp (pctxt,
            (OSOCTET*)pvalue->value.encoded.data,
            pvalue->value.encoded.numocts,
            pctxt->buffer.aligned);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
      pvalue->value.decoded = rtMemAlloc (pctxt, RANAP_ELEMENTARY_PROCEDURES[index].SuccessfulOutcomeSize);
      stat = RANAP_ELEMENTARY_PROCEDURES[index].decodeSuccessfulOutcome(pctxt, pvalue->value.decoded );
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
   }

   /* use -strict option to validate the "criticality" element */

   return stat;
}

/**************************************************************/
/*                                                            */
/*  UnsuccessfulOutcome                                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_UnsuccessfulOutcome (ASN1CTXT* pctxt, UnsuccessfulOutcome* pvalue)
{
   int stat = 0;
   ASN1CTXT lctxt;

   /* decode procedureCode */

   stat = asn1PD_ProcedureCode (pctxt, &pvalue->procedureCode);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   /* decode criticality */

   stat = asn1PD_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   /* decode value */

   stat = pd_OpenType (pctxt, &pvalue->value.encoded.data, &pvalue->value.encoded.numocts);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

    /* invoke table constraint function */

   rtCopyContext (&lctxt, pctxt);
   stat = asn1PDTC_UnsuccessfulOutcome (pctxt, pvalue);

   rtCopyContext (pctxt, &lctxt);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  UnsuccessfulOutcome                                       */
/*                                                            */
/**************************************************************/

EXTERN int asn1PDTC_UnsuccessfulOutcome (ASN1CTXT* pctxt,
   UnsuccessfulOutcome *pvalue)
{
   int stat = 0;
   int index = -1;

   /* check procedureCode */
   for(index = 0; index < RANAP_ELEMENTARY_PROCEDURES_Size; index++) {
      if(rtCmpTCUINT8(&pvalue->procedureCode, &RANAP_ELEMENTARY_PROCEDURES[index].procedureCode) == 0) {
         break;
      }
   }
   if(index == RANAP_ELEMENTARY_PROCEDURES_Size) return 0;

   /* check value */
   if(RANAP_ELEMENTARY_PROCEDURES[index].m.UnsuccessfulOutcomePresent)
   {
      stat = pd_setp (pctxt,
            (OSOCTET*)pvalue->value.encoded.data,
            pvalue->value.encoded.numocts,
            pctxt->buffer.aligned);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
      pvalue->value.decoded = rtMemAlloc (pctxt, RANAP_ELEMENTARY_PROCEDURES[index].UnsuccessfulOutcomeSize);
      stat = RANAP_ELEMENTARY_PROCEDURES[index].decodeUnsuccessfulOutcome(pctxt, pvalue->value.decoded );
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
   }

   /* use -strict option to validate the "criticality" element */

   return stat;
}

/**************************************************************/
/*                                                            */
/*  Outcome                                                   */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_Outcome (ASN1CTXT* pctxt, Outcome* pvalue)
{
   int stat = 0;
   ASN1CTXT lctxt;

   /* decode procedureCode */

   stat = asn1PD_ProcedureCode (pctxt, &pvalue->procedureCode);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   /* decode criticality */

   stat = asn1PD_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   /* decode value */

   stat = pd_OpenType (pctxt, &pvalue->value.encoded.data, &pvalue->value.encoded.numocts);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

    /* invoke table constraint function */

   rtCopyContext (&lctxt, pctxt);
   stat = asn1PDTC_Outcome (pctxt, pvalue);

   rtCopyContext (pctxt, &lctxt);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   return (stat);
}

/**************************************************************/
/*                                                            */
/*  Outcome                                                   */
/*                                                            */
/**************************************************************/

EXTERN int asn1PDTC_Outcome (ASN1CTXT* pctxt,
   Outcome *pvalue)
{
   int stat = 0;
   int index = -1;

   /* check procedureCode */
   for(index = 0; index < RANAP_ELEMENTARY_PROCEDURES_Size; index++) {
      if(rtCmpTCUINT8(&pvalue->procedureCode, &RANAP_ELEMENTARY_PROCEDURES[index].procedureCode) == 0) {
         break;
      }
   }
   if(index == RANAP_ELEMENTARY_PROCEDURES_Size) return 0;

   /* check value */
   if(RANAP_ELEMENTARY_PROCEDURES[index].m.OutcomePresent)
   {
      stat = pd_setp (pctxt,
            (OSOCTET*)pvalue->value.encoded.data,
            pvalue->value.encoded.numocts,
            pctxt->buffer.aligned);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
      pvalue->value.decoded = rtMemAlloc (pctxt, RANAP_ELEMENTARY_PROCEDURES[index].OutcomeSize);
      stat = RANAP_ELEMENTARY_PROCEDURES[index].decodeOutcome(pctxt, pvalue->value.decoded );
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
   }

   /* use -strict option to validate the "criticality" element */

   return stat;
}

/**************************************************************/
/*                                                            */
/*  RANAP_PDU                                                 */
/*                                                            */
/**************************************************************/

EXTERN int asn1PD_RANAP_PDU (ASN1CTXT* pctxt, RANAP_PDU* pvalue)
{
   int stat = 0;
   OSUINT32 ui;
   ASN1OpenType openType;
   OSBOOL extbit;

   /* extension bit */

   stat = PD_BIT (pctxt, &extbit);
   if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

   if (!extbit) {
      stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(3));
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
      else pvalue->t = ui + 1;

      switch (ui) {
         /* initiatingMessage */
         case 0:
            pvalue->u.initiatingMessage = rtMemAllocTypeZ (pctxt, InitiatingMessage);
            if (pvalue->u.initiatingMessage == NULL)
               return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

            stat = asn1PD_InitiatingMessage (pctxt, pvalue->u.initiatingMessage);
            if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

            break;

         /* successfulOutcome */
         case 1:
            pvalue->u.successfulOutcome = rtMemAllocTypeZ (pctxt, SuccessfulOutcome);
            if (pvalue->u.successfulOutcome == NULL)
               return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

            stat = asn1PD_SuccessfulOutcome (pctxt, pvalue->u.successfulOutcome);
            if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

            break;

         /* unsuccessfulOutcome */
         case 2:
            pvalue->u.unsuccessfulOutcome = rtMemAllocTypeZ (pctxt, UnsuccessfulOutcome);
            if (pvalue->u.unsuccessfulOutcome == NULL)
               return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

            stat = asn1PD_UnsuccessfulOutcome (pctxt, pvalue->u.unsuccessfulOutcome);
            if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

            break;

         /* outcome */
         case 3:
            pvalue->u.outcome = rtMemAllocTypeZ (pctxt, Outcome);
            if (pvalue->u.outcome == NULL)
               return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

            stat = asn1PD_Outcome (pctxt, pvalue->u.outcome);
            if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

            break;

         default:
            return LOG_ASN1ERR (pctxt, ASN_E_INVOPT);
      }
   }
   else {
      stat = pd_SmallNonNegWholeNumber (pctxt, &ui);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);
      else pvalue->t = ui + 5;

      stat = PD_BYTE_ALIGN (pctxt);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

      stat = pd_OpenType (pctxt, &openType.data, &openType.numocts);
      if (stat != 0) return LOG_ASN1ERR (pctxt, stat);

      pvalue->u.extElem1 = rtMemAllocType (pctxt, ASN1OpenType);
      if (pvalue->u.extElem1 == NULL)
         return LOG_ASN1ERR (pctxt, ASN_E_NOMEM);

      pvalue->u.extElem1->data = openType.data;
      pvalue->u.extElem1->numocts = openType.numocts;

   }

   return (stat);
}

