/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.83, Date: 20-Mar-2007.
 */
#ifndef RANAP_PDU_DESCRIPTIONS_H
#define RANAP_PDU_DESCRIPTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "asn1per.h"
#include "rtTable.h"
#include "RANAP-CommonDataTypes.h"
#include "RANAP-PDU-Contents.h"

/**************************************************************/
/*                                                            */
/*  _iu_Release_InitiatingMessage                             */
/*                                                            */
/**************************************************************/

typedef Iu_ReleaseCommand _iu_Release_InitiatingMessage;

EXTERN int asn1PE__iu_Release_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__iu_Release_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__iu_Release_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _iu_Release_InitiatingMessage* asn1Test__iu_Release_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _iu_Release_SuccessfulOutcome                             */
/*                                                            */
/**************************************************************/

typedef Iu_ReleaseComplete _iu_Release_SuccessfulOutcome;

EXTERN int asn1PE__iu_Release_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__iu_Release_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__iu_Release_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _iu_Release_SuccessfulOutcome* asn1Test__iu_Release_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationPreparation_InitiatingMessage                  */
/*                                                            */
/**************************************************************/

typedef RelocationRequired _relocationPreparation_InitiatingMessage;

EXTERN int asn1PE__relocationPreparation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationPreparation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationPreparation_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _relocationPreparation_InitiatingMessage* asn1Test__relocationPreparation_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationPreparation_SuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

typedef RelocationCommand _relocationPreparation_SuccessfulOutcome;

EXTERN int asn1PE__relocationPreparation_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationPreparation_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationPreparation_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _relocationPreparation_SuccessfulOutcome* asn1Test__relocationPreparation_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationPreparation_UnsuccessfulOutcome                */
/*                                                            */
/**************************************************************/

typedef RelocationPreparationFailure _relocationPreparation_UnsuccessfulOutcome;

EXTERN int asn1PE__relocationPreparation_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationPreparation_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationPreparation_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _relocationPreparation_UnsuccessfulOutcome* asn1Test__relocationPreparation_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationResourceAllocation_InitiatingMessage           */
/*                                                            */
/**************************************************************/

typedef RelocationRequest _relocationResourceAllocation_InitiatingMessage;

EXTERN int asn1PE__relocationResourceAllocation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationResourceAllocation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationResourceAllocation_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _relocationResourceAllocation_InitiatingMessage* asn1Test__relocationResourceAllocation_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationResourceAllocation_SuccessfulOutcome           */
/*                                                            */
/**************************************************************/

typedef RelocationRequestAcknowledge _relocationResourceAllocation_SuccessfulOutcome;

EXTERN int asn1PE__relocationResourceAllocation_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationResourceAllocation_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationResourceAllocation_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _relocationResourceAllocation_SuccessfulOutcome* asn1Test__relocationResourceAllocation_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationResourceAllocation_UnsuccessfulOutcome         */
/*                                                            */
/**************************************************************/

typedef RelocationFailure _relocationResourceAllocation_UnsuccessfulOutcome;

EXTERN int asn1PE__relocationResourceAllocation_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationResourceAllocation_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationResourceAllocation_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _relocationResourceAllocation_UnsuccessfulOutcome* asn1Test__relocationResourceAllocation_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationCancel_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

typedef RelocationCancel _relocationCancel_InitiatingMessage;

EXTERN int asn1PE__relocationCancel_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationCancel_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationCancel_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _relocationCancel_InitiatingMessage* asn1Test__relocationCancel_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationCancel_SuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

typedef RelocationCancelAcknowledge _relocationCancel_SuccessfulOutcome;

EXTERN int asn1PE__relocationCancel_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationCancel_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationCancel_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _relocationCancel_SuccessfulOutcome* asn1Test__relocationCancel_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _sRNS_ContextTransfer_InitiatingMessage                   */
/*                                                            */
/**************************************************************/

typedef SRNS_ContextRequest _sRNS_ContextTransfer_InitiatingMessage;

EXTERN int asn1PE__sRNS_ContextTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__sRNS_ContextTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__sRNS_ContextTransfer_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _sRNS_ContextTransfer_InitiatingMessage* asn1Test__sRNS_ContextTransfer_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _sRNS_ContextTransfer_SuccessfulOutcome                   */
/*                                                            */
/**************************************************************/

typedef SRNS_ContextResponse _sRNS_ContextTransfer_SuccessfulOutcome;

EXTERN int asn1PE__sRNS_ContextTransfer_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__sRNS_ContextTransfer_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__sRNS_ContextTransfer_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _sRNS_ContextTransfer_SuccessfulOutcome* asn1Test__sRNS_ContextTransfer_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _securityModeControl_InitiatingMessage                    */
/*                                                            */
/**************************************************************/

typedef SecurityModeCommand _securityModeControl_InitiatingMessage;

EXTERN int asn1PE__securityModeControl_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__securityModeControl_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__securityModeControl_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _securityModeControl_InitiatingMessage* asn1Test__securityModeControl_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _securityModeControl_SuccessfulOutcome                    */
/*                                                            */
/**************************************************************/

typedef SecurityModeComplete _securityModeControl_SuccessfulOutcome;

EXTERN int asn1PE__securityModeControl_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__securityModeControl_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__securityModeControl_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _securityModeControl_SuccessfulOutcome* asn1Test__securityModeControl_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _securityModeControl_UnsuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

typedef SecurityModeReject _securityModeControl_UnsuccessfulOutcome;

EXTERN int asn1PE__securityModeControl_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__securityModeControl_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__securityModeControl_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _securityModeControl_UnsuccessfulOutcome* asn1Test__securityModeControl_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _dataVolumeReport_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

typedef DataVolumeReportRequest _dataVolumeReport_InitiatingMessage;

EXTERN int asn1PE__dataVolumeReport_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__dataVolumeReport_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__dataVolumeReport_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _dataVolumeReport_InitiatingMessage* asn1Test__dataVolumeReport_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _dataVolumeReport_SuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

typedef DataVolumeReport _dataVolumeReport_SuccessfulOutcome;

EXTERN int asn1PE__dataVolumeReport_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__dataVolumeReport_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__dataVolumeReport_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _dataVolumeReport_SuccessfulOutcome* asn1Test__dataVolumeReport_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _reset_InitiatingMessage                                  */
/*                                                            */
/**************************************************************/

typedef Reset _reset_InitiatingMessage;

EXTERN int asn1PE__reset_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__reset_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__reset_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _reset_InitiatingMessage* asn1Test__reset_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _reset_SuccessfulOutcome                                  */
/*                                                            */
/**************************************************************/

typedef ResetAcknowledge _reset_SuccessfulOutcome;

EXTERN int asn1PE__reset_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__reset_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__reset_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _reset_SuccessfulOutcome* asn1Test__reset_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _rAB_ReleaseRequest_InitiatingMessage                     */
/*                                                            */
/**************************************************************/

typedef RAB_ReleaseRequest _rAB_ReleaseRequest_InitiatingMessage;

EXTERN int asn1PE__rAB_ReleaseRequest_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__rAB_ReleaseRequest_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__rAB_ReleaseRequest_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _rAB_ReleaseRequest_InitiatingMessage* asn1Test__rAB_ReleaseRequest_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _iu_ReleaseRequest_InitiatingMessage                      */
/*                                                            */
/**************************************************************/

typedef Iu_ReleaseRequest _iu_ReleaseRequest_InitiatingMessage;

EXTERN int asn1PE__iu_ReleaseRequest_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__iu_ReleaseRequest_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__iu_ReleaseRequest_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _iu_ReleaseRequest_InitiatingMessage* asn1Test__iu_ReleaseRequest_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationDetect_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

typedef RelocationDetect _relocationDetect_InitiatingMessage;

EXTERN int asn1PE__relocationDetect_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationDetect_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationDetect_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _relocationDetect_InitiatingMessage* asn1Test__relocationDetect_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _relocationComplete_InitiatingMessage                     */
/*                                                            */
/**************************************************************/

typedef RelocationComplete _relocationComplete_InitiatingMessage;

EXTERN int asn1PE__relocationComplete_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__relocationComplete_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__relocationComplete_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _relocationComplete_InitiatingMessage* asn1Test__relocationComplete_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _paging_InitiatingMessage                                 */
/*                                                            */
/**************************************************************/

typedef Paging _paging_InitiatingMessage;

EXTERN int asn1PE__paging_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__paging_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__paging_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _paging_InitiatingMessage* asn1Test__paging_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _commonID_InitiatingMessage                               */
/*                                                            */
/**************************************************************/

typedef CommonID _commonID_InitiatingMessage;

EXTERN int asn1PE__commonID_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__commonID_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__commonID_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _commonID_InitiatingMessage* asn1Test__commonID_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _cN_InvokeTrace_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

typedef CN_InvokeTrace _cN_InvokeTrace_InitiatingMessage;

EXTERN int asn1PE__cN_InvokeTrace_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__cN_InvokeTrace_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__cN_InvokeTrace_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _cN_InvokeTrace_InitiatingMessage* asn1Test__cN_InvokeTrace_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _cN_DeactivateTrace_InitiatingMessage                     */
/*                                                            */
/**************************************************************/

typedef CN_DeactivateTrace _cN_DeactivateTrace_InitiatingMessage;

EXTERN int asn1PE__cN_DeactivateTrace_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__cN_DeactivateTrace_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__cN_DeactivateTrace_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _cN_DeactivateTrace_InitiatingMessage* asn1Test__cN_DeactivateTrace_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _locationReportingControl_InitiatingMessage               */
/*                                                            */
/**************************************************************/

typedef LocationReportingControl _locationReportingControl_InitiatingMessage;

EXTERN int asn1PE__locationReportingControl_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__locationReportingControl_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__locationReportingControl_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _locationReportingControl_InitiatingMessage* asn1Test__locationReportingControl_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _locationReport_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

typedef LocationReport _locationReport_InitiatingMessage;

EXTERN int asn1PE__locationReport_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__locationReport_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__locationReport_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _locationReport_InitiatingMessage* asn1Test__locationReport_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _initialUE_Message_InitiatingMessage                      */
/*                                                            */
/**************************************************************/

typedef InitialUE_Message _initialUE_Message_InitiatingMessage;

EXTERN int asn1PE__initialUE_Message_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__initialUE_Message_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__initialUE_Message_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _initialUE_Message_InitiatingMessage* asn1Test__initialUE_Message_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _directTransfer_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

typedef DirectTransfer _directTransfer_InitiatingMessage;

EXTERN int asn1PE__directTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__directTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__directTransfer_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _directTransfer_InitiatingMessage* asn1Test__directTransfer_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _overloadControl_InitiatingMessage                        */
/*                                                            */
/**************************************************************/

typedef Overload _overloadControl_InitiatingMessage;

EXTERN int asn1PE__overloadControl_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__overloadControl_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__overloadControl_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _overloadControl_InitiatingMessage* asn1Test__overloadControl_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _errorIndication_InitiatingMessage                        */
/*                                                            */
/**************************************************************/

typedef ErrorIndication _errorIndication_InitiatingMessage;

EXTERN int asn1PE__errorIndication_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__errorIndication_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__errorIndication_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _errorIndication_InitiatingMessage* asn1Test__errorIndication_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _sRNS_DataForward_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

typedef SRNS_DataForwardCommand _sRNS_DataForward_InitiatingMessage;

EXTERN int asn1PE__sRNS_DataForward_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__sRNS_DataForward_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__sRNS_DataForward_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _sRNS_DataForward_InitiatingMessage* asn1Test__sRNS_DataForward_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _forwardSRNS_Context_InitiatingMessage                    */
/*                                                            */
/**************************************************************/

typedef ForwardSRNS_Context _forwardSRNS_Context_InitiatingMessage;

EXTERN int asn1PE__forwardSRNS_Context_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__forwardSRNS_Context_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__forwardSRNS_Context_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _forwardSRNS_Context_InitiatingMessage* asn1Test__forwardSRNS_Context_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _rAB_Assignment_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

typedef RAB_AssignmentRequest _rAB_Assignment_InitiatingMessage;

EXTERN int asn1PE__rAB_Assignment_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__rAB_Assignment_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__rAB_Assignment_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _rAB_Assignment_InitiatingMessage* asn1Test__rAB_Assignment_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _rAB_Assignment_Outcome                                   */
/*                                                            */
/**************************************************************/

typedef RAB_AssignmentResponse _rAB_Assignment_Outcome;

EXTERN int asn1PE__rAB_Assignment_Outcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__rAB_Assignment_Outcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__rAB_Assignment_Outcome
   (const char* name, void* pvalue_);

EXTERN _rAB_Assignment_Outcome* asn1Test__rAB_Assignment_Outcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _privateMessage_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

typedef PrivateMessage _privateMessage_InitiatingMessage;

EXTERN int asn1PE__privateMessage_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__privateMessage_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__privateMessage_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _privateMessage_InitiatingMessage* asn1Test__privateMessage_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _resetResource_InitiatingMessage                          */
/*                                                            */
/**************************************************************/

typedef ResetResource _resetResource_InitiatingMessage;

EXTERN int asn1PE__resetResource_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__resetResource_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__resetResource_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _resetResource_InitiatingMessage* asn1Test__resetResource_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _resetResource_SuccessfulOutcome                          */
/*                                                            */
/**************************************************************/

typedef ResetResourceAcknowledge _resetResource_SuccessfulOutcome;

EXTERN int asn1PE__resetResource_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__resetResource_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__resetResource_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _resetResource_SuccessfulOutcome* asn1Test__resetResource_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _rANAP_Relocation_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

typedef RANAP_RelocationInformation _rANAP_Relocation_InitiatingMessage;

EXTERN int asn1PE__rANAP_Relocation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__rANAP_Relocation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__rANAP_Relocation_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _rANAP_Relocation_InitiatingMessage* asn1Test__rANAP_Relocation_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _rAB_ModifyRequest_InitiatingMessage                      */
/*                                                            */
/**************************************************************/

typedef RAB_ModifyRequest _rAB_ModifyRequest_InitiatingMessage;

EXTERN int asn1PE__rAB_ModifyRequest_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__rAB_ModifyRequest_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__rAB_ModifyRequest_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _rAB_ModifyRequest_InitiatingMessage* asn1Test__rAB_ModifyRequest_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _locationRelatedData_InitiatingMessage                    */
/*                                                            */
/**************************************************************/

typedef LocationRelatedDataRequest _locationRelatedData_InitiatingMessage;

EXTERN int asn1PE__locationRelatedData_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__locationRelatedData_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__locationRelatedData_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _locationRelatedData_InitiatingMessage* asn1Test__locationRelatedData_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _locationRelatedData_SuccessfulOutcome                    */
/*                                                            */
/**************************************************************/

typedef LocationRelatedDataResponse _locationRelatedData_SuccessfulOutcome;

EXTERN int asn1PE__locationRelatedData_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__locationRelatedData_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__locationRelatedData_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _locationRelatedData_SuccessfulOutcome* asn1Test__locationRelatedData_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _locationRelatedData_UnsuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

typedef LocationRelatedDataFailure _locationRelatedData_UnsuccessfulOutcome;

EXTERN int asn1PE__locationRelatedData_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__locationRelatedData_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__locationRelatedData_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _locationRelatedData_UnsuccessfulOutcome* asn1Test__locationRelatedData_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _informationTransfer_InitiatingMessage                    */
/*                                                            */
/**************************************************************/

typedef InformationTransferIndication _informationTransfer_InitiatingMessage;

EXTERN int asn1PE__informationTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__informationTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__informationTransfer_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _informationTransfer_InitiatingMessage* asn1Test__informationTransfer_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _informationTransfer_SuccessfulOutcome                    */
/*                                                            */
/**************************************************************/

typedef InformationTransferConfirmation _informationTransfer_SuccessfulOutcome;

EXTERN int asn1PE__informationTransfer_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__informationTransfer_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__informationTransfer_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _informationTransfer_SuccessfulOutcome* asn1Test__informationTransfer_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _informationTransfer_UnsuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

typedef InformationTransferFailure _informationTransfer_UnsuccessfulOutcome;

EXTERN int asn1PE__informationTransfer_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__informationTransfer_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__informationTransfer_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _informationTransfer_UnsuccessfulOutcome* asn1Test__informationTransfer_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _uESpecificInformation_InitiatingMessage                  */
/*                                                            */
/**************************************************************/

typedef UESpecificInformationIndication _uESpecificInformation_InitiatingMessage;

EXTERN int asn1PE__uESpecificInformation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__uESpecificInformation_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__uESpecificInformation_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _uESpecificInformation_InitiatingMessage* asn1Test__uESpecificInformation_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _directInformationTransfer_InitiatingMessage              */
/*                                                            */
/**************************************************************/

typedef DirectInformationTransfer _directInformationTransfer_InitiatingMessage;

EXTERN int asn1PE__directInformationTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__directInformationTransfer_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__directInformationTransfer_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _directInformationTransfer_InitiatingMessage* asn1Test__directInformationTransfer_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _uplinkInformationExchange_InitiatingMessage              */
/*                                                            */
/**************************************************************/

typedef UplinkInformationExchangeRequest _uplinkInformationExchange_InitiatingMessage;

EXTERN int asn1PE__uplinkInformationExchange_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__uplinkInformationExchange_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__uplinkInformationExchange_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _uplinkInformationExchange_InitiatingMessage* asn1Test__uplinkInformationExchange_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _uplinkInformationExchange_SuccessfulOutcome              */
/*                                                            */
/**************************************************************/

typedef UplinkInformationExchangeResponse _uplinkInformationExchange_SuccessfulOutcome;

EXTERN int asn1PE__uplinkInformationExchange_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__uplinkInformationExchange_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__uplinkInformationExchange_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _uplinkInformationExchange_SuccessfulOutcome* asn1Test__uplinkInformationExchange_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _uplinkInformationExchange_UnsuccessfulOutcome            */
/*                                                            */
/**************************************************************/

typedef UplinkInformationExchangeFailure _uplinkInformationExchange_UnsuccessfulOutcome;

EXTERN int asn1PE__uplinkInformationExchange_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__uplinkInformationExchange_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__uplinkInformationExchange_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _uplinkInformationExchange_UnsuccessfulOutcome* asn1Test__uplinkInformationExchange_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStart_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

typedef MBMSSessionStart _mBMSSessionStart_InitiatingMessage;

EXTERN int asn1PE__mBMSSessionStart_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSSessionStart_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSSessionStart_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _mBMSSessionStart_InitiatingMessage* asn1Test__mBMSSessionStart_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStart_SuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

typedef MBMSSessionStartResponse _mBMSSessionStart_SuccessfulOutcome;

EXTERN int asn1PE__mBMSSessionStart_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSSessionStart_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSSessionStart_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSSessionStart_SuccessfulOutcome* asn1Test__mBMSSessionStart_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStart_UnsuccessfulOutcome                     */
/*                                                            */
/**************************************************************/

typedef MBMSSessionStartFailure _mBMSSessionStart_UnsuccessfulOutcome;

EXTERN int asn1PE__mBMSSessionStart_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSSessionStart_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSSessionStart_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSSessionStart_UnsuccessfulOutcome* asn1Test__mBMSSessionStart_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSSessionUpdate_InitiatingMessage                      */
/*                                                            */
/**************************************************************/

typedef MBMSSessionUpdate _mBMSSessionUpdate_InitiatingMessage;

EXTERN int asn1PE__mBMSSessionUpdate_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSSessionUpdate_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSSessionUpdate_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _mBMSSessionUpdate_InitiatingMessage* asn1Test__mBMSSessionUpdate_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSSessionUpdate_SuccessfulOutcome                      */
/*                                                            */
/**************************************************************/

typedef MBMSSessionUpdateResponse _mBMSSessionUpdate_SuccessfulOutcome;

EXTERN int asn1PE__mBMSSessionUpdate_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSSessionUpdate_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSSessionUpdate_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSSessionUpdate_SuccessfulOutcome* asn1Test__mBMSSessionUpdate_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSSessionUpdate_UnsuccessfulOutcome                    */
/*                                                            */
/**************************************************************/

typedef MBMSSessionUpdateFailure _mBMSSessionUpdate_UnsuccessfulOutcome;

EXTERN int asn1PE__mBMSSessionUpdate_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSSessionUpdate_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSSessionUpdate_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSSessionUpdate_UnsuccessfulOutcome* asn1Test__mBMSSessionUpdate_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStop_InitiatingMessage                        */
/*                                                            */
/**************************************************************/

typedef MBMSSessionStop _mBMSSessionStop_InitiatingMessage;

EXTERN int asn1PE__mBMSSessionStop_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSSessionStop_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSSessionStop_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _mBMSSessionStop_InitiatingMessage* asn1Test__mBMSSessionStop_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSSessionStop_SuccessfulOutcome                        */
/*                                                            */
/**************************************************************/

typedef MBMSSessionStopResponse _mBMSSessionStop_SuccessfulOutcome;

EXTERN int asn1PE__mBMSSessionStop_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSSessionStop_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSSessionStop_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSSessionStop_SuccessfulOutcome* asn1Test__mBMSSessionStop_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSUELinking_InitiatingMessage                          */
/*                                                            */
/**************************************************************/

typedef MBMSUELinkingRequest _mBMSUELinking_InitiatingMessage;

EXTERN int asn1PE__mBMSUELinking_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSUELinking_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSUELinking_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _mBMSUELinking_InitiatingMessage* asn1Test__mBMSUELinking_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSUELinking_Outcome                                    */
/*                                                            */
/**************************************************************/

typedef MBMSUELinkingResponse _mBMSUELinking_Outcome;

EXTERN int asn1PE__mBMSUELinking_Outcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSUELinking_Outcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSUELinking_Outcome
   (const char* name, void* pvalue_);

EXTERN _mBMSUELinking_Outcome* asn1Test__mBMSUELinking_Outcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSRegistration_InitiatingMessage                       */
/*                                                            */
/**************************************************************/

typedef MBMSRegistrationRequest _mBMSRegistration_InitiatingMessage;

EXTERN int asn1PE__mBMSRegistration_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSRegistration_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSRegistration_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _mBMSRegistration_InitiatingMessage* asn1Test__mBMSRegistration_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSRegistration_SuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

typedef MBMSRegistrationResponse _mBMSRegistration_SuccessfulOutcome;

EXTERN int asn1PE__mBMSRegistration_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSRegistration_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSRegistration_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSRegistration_SuccessfulOutcome* asn1Test__mBMSRegistration_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSRegistration_UnsuccessfulOutcome                     */
/*                                                            */
/**************************************************************/

typedef MBMSRegistrationFailure _mBMSRegistration_UnsuccessfulOutcome;

EXTERN int asn1PE__mBMSRegistration_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSRegistration_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSRegistration_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSRegistration_UnsuccessfulOutcome* asn1Test__mBMSRegistration_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSCNDe_Registration_InitiatingMessage                  */
/*                                                            */
/**************************************************************/

typedef MBMSCNDe_RegistrationRequest _mBMSCNDe_Registration_InitiatingMessage;

EXTERN int asn1PE__mBMSCNDe_Registration_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSCNDe_Registration_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSCNDe_Registration_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _mBMSCNDe_Registration_InitiatingMessage* asn1Test__mBMSCNDe_Registration_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSCNDe_Registration_SuccessfulOutcome                  */
/*                                                            */
/**************************************************************/

typedef MBMSCNDe_RegistrationResponse _mBMSCNDe_Registration_SuccessfulOutcome;

EXTERN int asn1PE__mBMSCNDe_Registration_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSCNDe_Registration_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSCNDe_Registration_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSCNDe_Registration_SuccessfulOutcome* asn1Test__mBMSCNDe_Registration_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSRABEstablishmentIndication_InitiatingMessage         */
/*                                                            */
/**************************************************************/

typedef MBMSRABEstablishmentIndication _mBMSRABEstablishmentIndication_InitiatingMessage;

EXTERN int asn1PE__mBMSRABEstablishmentIndication_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSRABEstablishmentIndication_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSRABEstablishmentIndication_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _mBMSRABEstablishmentIndication_InitiatingMessage* asn1Test__mBMSRABEstablishmentIndication_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSRABRelease_InitiatingMessage                         */
/*                                                            */
/**************************************************************/

typedef MBMSRABReleaseRequest _mBMSRABRelease_InitiatingMessage;

EXTERN int asn1PE__mBMSRABRelease_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSRABRelease_InitiatingMessage (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSRABRelease_InitiatingMessage
   (const char* name, void* pvalue_);

EXTERN _mBMSRABRelease_InitiatingMessage* asn1Test__mBMSRABRelease_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSRABRelease_SuccessfulOutcome                         */
/*                                                            */
/**************************************************************/

typedef MBMSRABRelease _mBMSRABRelease_SuccessfulOutcome;

EXTERN int asn1PE__mBMSRABRelease_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSRABRelease_SuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSRABRelease_SuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSRABRelease_SuccessfulOutcome* asn1Test__mBMSRABRelease_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  _mBMSRABRelease_UnsuccessfulOutcome                       */
/*                                                            */
/**************************************************************/

typedef MBMSRABReleaseFailure _mBMSRABRelease_UnsuccessfulOutcome;

EXTERN int asn1PE__mBMSRABRelease_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN int asn1PD__mBMSRABRelease_UnsuccessfulOutcome (ASN1CTXT* pctxt, void* pvalue_);

EXTERN void asn1Print__mBMSRABRelease_UnsuccessfulOutcome
   (const char* name, void* pvalue_);

EXTERN _mBMSRABRelease_UnsuccessfulOutcome* asn1Test__mBMSRABRelease_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  InitiatingMessage                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN InitiatingMessage {
   ProcedureCode procedureCode;
   Criticality criticality;
   Asn1Object value;
} InitiatingMessage;

EXTERN int asn1PE_InitiatingMessage (ASN1CTXT* pctxt, InitiatingMessage* pvalue);

EXTERN int asn1PD_InitiatingMessage (ASN1CTXT* pctxt, InitiatingMessage* pvalue);

EXTERN int asn1PETC_InitiatingMessage (ASN1CTXT* pctxt,
   InitiatingMessage *pvalue);

EXTERN int asn1PDTC_InitiatingMessage (ASN1CTXT* pctxt,
   InitiatingMessage *pvalue);

EXTERN void asn1Print_InitiatingMessage
   (const char* name, InitiatingMessage* pvalue);

EXTERN InitiatingMessage* asn1Test_InitiatingMessage
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  SuccessfulOutcome                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN SuccessfulOutcome {
   ProcedureCode procedureCode;
   Criticality criticality;
   Asn1Object value;
} SuccessfulOutcome;

EXTERN int asn1PE_SuccessfulOutcome (ASN1CTXT* pctxt, SuccessfulOutcome* pvalue);

EXTERN int asn1PD_SuccessfulOutcome (ASN1CTXT* pctxt, SuccessfulOutcome* pvalue);

EXTERN int asn1PETC_SuccessfulOutcome (ASN1CTXT* pctxt,
   SuccessfulOutcome *pvalue);

EXTERN int asn1PDTC_SuccessfulOutcome (ASN1CTXT* pctxt,
   SuccessfulOutcome *pvalue);

EXTERN void asn1Print_SuccessfulOutcome
   (const char* name, SuccessfulOutcome* pvalue);

EXTERN SuccessfulOutcome* asn1Test_SuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  UnsuccessfulOutcome                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN UnsuccessfulOutcome {
   ProcedureCode procedureCode;
   Criticality criticality;
   Asn1Object value;
} UnsuccessfulOutcome;

EXTERN int asn1PE_UnsuccessfulOutcome (ASN1CTXT* pctxt, UnsuccessfulOutcome* pvalue);

EXTERN int asn1PD_UnsuccessfulOutcome (ASN1CTXT* pctxt, UnsuccessfulOutcome* pvalue);

EXTERN int asn1PETC_UnsuccessfulOutcome (ASN1CTXT* pctxt,
   UnsuccessfulOutcome *pvalue);

EXTERN int asn1PDTC_UnsuccessfulOutcome (ASN1CTXT* pctxt,
   UnsuccessfulOutcome *pvalue);

EXTERN void asn1Print_UnsuccessfulOutcome
   (const char* name, UnsuccessfulOutcome* pvalue);

EXTERN UnsuccessfulOutcome* asn1Test_UnsuccessfulOutcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  Outcome                                                   */
/*                                                            */
/**************************************************************/

typedef struct EXTERN Outcome {
   ProcedureCode procedureCode;
   Criticality criticality;
   Asn1Object value;
} Outcome;

EXTERN int asn1PE_Outcome (ASN1CTXT* pctxt, Outcome* pvalue);

EXTERN int asn1PD_Outcome (ASN1CTXT* pctxt, Outcome* pvalue);

EXTERN int asn1PETC_Outcome (ASN1CTXT* pctxt,
   Outcome *pvalue);

EXTERN int asn1PDTC_Outcome (ASN1CTXT* pctxt,
   Outcome *pvalue);

EXTERN void asn1Print_Outcome
   (const char* name, Outcome* pvalue);

EXTERN Outcome* asn1Test_Outcome
   (ASN1CTXT* pctxt);

/**************************************************************/
/*                                                            */
/*  RANAP_PDU                                                 */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_RANAP_PDU_initiatingMessage   1
#define T_RANAP_PDU_successfulOutcome   2
#define T_RANAP_PDU_unsuccessfulOutcome 3
#define T_RANAP_PDU_outcome             4
#define T_RANAP_PDU_extElem1            5

typedef struct EXTERN RANAP_PDU {
   int t;
   union {
      /* t = 1 */
      InitiatingMessage *initiatingMessage;
      /* t = 2 */
      SuccessfulOutcome *successfulOutcome;
      /* t = 3 */
      UnsuccessfulOutcome *unsuccessfulOutcome;
      /* t = 4 */
      Outcome *outcome;
      /* t = 5 */
      ASN1OpenType *extElem1;
   } u;
} RANAP_PDU;

EXTERN int asn1PE_RANAP_PDU (ASN1CTXT* pctxt, RANAP_PDU* pvalue);

EXTERN int asn1PD_RANAP_PDU (ASN1CTXT* pctxt, RANAP_PDU* pvalue);

EXTERN void asn1Print_RANAP_PDU
   (const char* name, RANAP_PDU* pvalue);

EXTERN RANAP_PDU* asn1Test_RANAP_PDU
   (ASN1CTXT* pctxt);

#ifdef __cplusplus
}
#endif

#endif
